import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function playTTS(text: string, lang: string = 'nl-NL') {
  if (!('speechSynthesis' in window)) return;
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = lang;
  utterance.rate = 0.75;

  const voices = window.speechSynthesis.getVoices();
  const femaleVoice = voices.find(v =>
    v.lang.startsWith(lang.split('-')[0]) && /female|vrouw|woman|zira|hazel|fiona|anna|ellen|lotte/i.test(v.name)
  ) || voices.find(v =>
    v.lang.startsWith(lang.split('-')[0]) && !/male|man|david|mark|daniel/i.test(v.name)
  ) || voices.find(v =>
    v.lang.startsWith(lang.split('-')[0])
  );

  if (femaleVoice) utterance.voice = femaleVoice;
  window.speechSynthesis.speak(utterance);
}

export async function translateDutchToRussian(text: string): Promise<string> {
  const dictionary: Record<string, string> = {
    'appel': 'яблоко',
    'banaan': 'банан',
    'fiets': 'велосипед',
    'hond': 'собака',
    'kat': 'кошка',
    'huis': 'дом',
    'water': 'вода',
    'brood': 'хлеб',
    'kaas': 'сыр',
    'melk': 'молоко',
    'auto': 'машина',
    'trein': 'поезд',
    'lopen': 'идти',
    'eten': 'есть',
    'drinken': 'пить',
    'boek': 'книга',
    'tafel': 'стол',
    'stoel': 'стул',
    'raam': 'окно',
    'deur': 'дверь',
    'vriend': 'друг',
    'school': 'школа',
    'werk': 'работа',
    'stad': 'город',
    'land': 'страна',
    'lucht': 'воздух',
    'zon': 'солнце',
    'maan': 'луна',
    'ster': 'звезда',
    'boom': 'дерево',
    'bloem': 'цветок',
    'gras': 'трава',
    'zee': 'море',
    'rivier': 'река',
    'berg': 'гора',
    'dal': 'долина',
    'weg': 'путь',
    'tijd': 'время',
    'dag': 'день',
    'nacht': 'ночь',
    'morgen': 'утро',
    'avond': 'вечер',
    'vandaag': 'сегодня',
    'gisteren': 'вчера',
    'morgen (tomorrow)': 'завтра',
    'altijd': 'всегда',
    'nooit': 'никогда',
    'vaak': 'часто',
    'soms': 'иногда',
    'nu': 'сейчас',
    'toen': 'тогда',
    'hier': 'здесь',
    'daar': 'там',
    'waar': 'где',
    'wie': 'кто',
    'wat': 'что',
    'waarom': 'почему',
    'hoe': 'как',
    'hoeveel': 'сколько',
    'welke': 'какой',
    'groot': 'большой',
    'klein': 'маленький',
    'goed': 'хороший',
    'slecht': 'плохой',
    'mooi': 'красивый',
    'lelijk': 'уродливый',
    'nieuw': 'новый',
    'oud': 'старый',
    'jong': 'молодой',
    'warm': 'теплый',
    'koud': 'холодный',
    'snel': 'быстрый',
    'langzaam': 'медленный',
    'makkelijk': 'легкий',
    'moeilijk': 'трудный',
    'rijk': 'богатый',
    'arm': 'бедный',
    'blij': 'счастливый',
    'verdrietig': 'грустный',
    'boos': 'злой',
    'bang': 'испуганный',
    'moe': 'усталый',
    'honger': 'голод',
    'dorst': 'жажда',
    'spreken': 'говорить',
    'luisteren': 'слушать',
    'kijken': 'смотреть',
    'zien': 'видеть',
    'horen': 'слышать',
    'ruiken': 'нюхать',
    'proeven': 'пробовать на вкус',
    'voelen': 'чувствовать',
    'denken': 'думать',
    'geloven': 'верить',
    'weten': 'знать',
    'begrijpen': 'понимать',
    'leren': 'учить',
    'studeren': 'изучать',
    'schrijven': 'писать',
    'lezen': 'читать',
    'tellen': 'считать',
    'rekenen': 'вычислять',
    'werken': 'работать',
    'spelen': 'играть',
    'rusten': 'отдыхать',
    'slapen': 'спать',
    'dromen': 'мечтать',
    'wakker worden': 'просыпаться',
    'opstaan': 'вставать',
    'wassen': 'мыться',
    'douchen': 'принимать душ',
    'poetsen': 'чистить',
    'kleden': 'одеваться',
    'koken': 'готовить',
    'bakken': 'печь',
    'braden': 'жарить',
    'snijden': 'резать',
    'roeren': 'мешать',
    'proeven (cook)': 'пробовать',
    'serveren': 'подавать',
    'bestellen': 'заказывать',
    'betalen': 'платить',
    'kopen': 'покупать',
    'verkopen': 'продавать',
    'ruilen': 'менять',
    'geven': 'давать',
    'krijgen': 'получать',
    'nemen': 'брать',
    'houden (keep)': 'держать',
    'vallen': 'падать',
    'vangen': 'ловить',
    'stoppen': 'останавливаться',
    'wachten': 'ждать',
    'zoeken': 'искать',
    'vinden': 'находить',
    'verliezen': 'терять',
    'winnen': 'побеждать',
    'beginnen': 'начинать',
    'eindigen': 'заканчивать',
    'openen': 'открывать',
    'sluiten': 'закрывать',
    'vragen': 'спрашивать',
    'antwoorden': 'отвечать',
    'zeggen': 'сказать',
    'vertellen': 'рассказывать',
    'lachen': 'смеяться',
    'huilen': 'плакать',
    'roepen': 'звать',
    'schreeuwen': 'кричать',
    'zingen': 'петь',
    'dansen': 'танцевать',
    'reizen': 'путешествовать',
    'rijden': 'ездить',
    'vliegen': 'летать',
    'varen': 'плавать (на судне)',
    'zwemmen': 'плавать',
    'rennen': 'бежать',
    'wandelen': 'гулять',
    'fietsen': 'кататься на велосипеде',
    'vallen (fall)': 'падать',
    'springen': 'прыгать',
    'klimmen': 'лазить',
    'zitten': 'сидеть',
    'staan': 'стоять',
    'liggen': 'лежать',
    'buigen': 'кланяться',
    'trekken': 'тянуть',
    'duwen': 'толкать',
    'dragen (carry)': 'носить',
    'gooien': 'бросать',
    'vangen (catch)': 'ловить',
    'slaan': 'бить',
    'schoppen': 'пинать',
    'bijten (bite)': 'кусать',
    'likken': 'лизать',
    'ademen': 'дышать',
    'slikken': 'глотать',
    'kauwen': 'жевать',
    'ruiken (smell)': 'пахнуть',
    'zweten': 'потеть',
    'bloeden': 'кровоточить',
    'trillen': 'дрожать',
    'sterven (die)': 'умирать',
    'geboren worden': 'рождаться',
    'leven': 'жить',
    'groeien': 'расти',
    'veranderen': 'меняться',
    'blijven (stay)': 'оставаться',
    'worden': 'становиться',
    'zijn': 'быть',
    'hebben': 'иметь',
    'kunnen': 'мочь',
    'moeten': 'быть должным',
    'willen': 'хотеть',
    'mogen': 'иметь разрешение',
    'zullen': 'вспомогательный глагол будущего времени',
    'durven': 'сметь',
    'hoeven': 'нуждаться',
    'laten (let)': 'позволять'
  };
  
  const normalized = text.toLowerCase().trim();
  return dictionary[normalized] || '';
}
