export const CONTEXT_SENTENCES = [
  { dutch: "Ik heb een hond en een kat.", english: "I have a dog and a cat.", level: "A1" },
  { dutch: "De hond loopt in het park.", english: "The dog walks in the park.", level: "A1" },
  { dutch: "Mijn hond heet Max.", english: "My dog is called Max.", level: "A1" },
  { dutch: "De kat slaapt op de bank.", english: "The cat sleeps on the couch.", level: "A1" },
  { dutch: "De kat drinkt melk.", english: "The cat drinks milk.", level: "A1" },
  { dutch: "Ik woon in een groot huis.", english: "I live in a big house.", level: "A1" },
  { dutch: "Het huis heeft drie kamers.", english: "The house has three rooms.", level: "A1" },
  { dutch: "Dit is mijn huis.", english: "This is my house.", level: "A1" },
  { dutch: "Ik ga met de fiets naar school.", english: "I go to school by bicycle.", level: "A1" },
  { dutch: "De fiets staat in de tuin.", english: "The bicycle is in the garden.", level: "A1" },
  { dutch: "Mijn fiets is rood.", english: "My bicycle is red.", level: "A1" },
  { dutch: "Is deze fiets van jou?", english: "Is this bicycle yours?", level: "A2" },
  { dutch: "Mag ik een glas water?", english: "Can I have a glass of water?", level: "A1" },
  { dutch: "Het water is koud.", english: "The water is cold.", level: "A1" },
  { dutch: "Ik drink water bij het eten.", english: "I drink water with my meal.", level: "A1" },
  { dutch: "Wil je brood met kaas?", english: "Would you like bread with cheese?", level: "A1" },
  { dutch: "Het brood is vers.", english: "The bread is fresh.", level: "A1" },
  { dutch: "Ik eet brood voor het ontbijt.", english: "I eat bread for breakfast.", level: "A1" },
  { dutch: "Nederlandse kaas is beroemd.", english: "Dutch cheese is famous.", level: "A2" },
  { dutch: "Wil je een stuk kaas?", english: "Would you like a piece of cheese?", level: "A1" },
  { dutch: "De melk staat in de koelkast.", english: "The milk is in the fridge.", level: "A1" },
  { dutch: "Ik drink melk bij het ontbijt.", english: "I drink milk at breakfast.", level: "A1" },
  { dutch: "Wil je een appel?", english: "Would you like an apple?", level: "A1" },
  { dutch: "De appel is groen.", english: "The apple is green.", level: "A1" },
  { dutch: "Ik eet elke dag een appel.", english: "I eat an apple every day.", level: "A1" },
  { dutch: "De banaan is geel.", english: "The banana is yellow.", level: "A1" },
  { dutch: "Goedemorgen, hoe gaat het?", english: "Good morning, how are you?", level: "A1" },
  { dutch: "Goedemorgen, het is mooi weer.", english: "Good morning, the weather is nice.", level: "A1" },
  { dutch: "Dank u voor de hulp.", english: "Thank you for the help.", level: "A1" },
  { dutch: "Dank u wel, meneer.", english: "Thank you, sir.", level: "A1" },
  { dutch: "Alstublieft, hier is uw koffie.", english: "Here you go, here is your coffee.", level: "A1" },
  { dutch: "Ja, ik spreek een beetje Nederlands.", english: "Yes, I speak a little Dutch.", level: "A1" },
  { dutch: "Nee, ik begrijp het niet.", english: "No, I don't understand.", level: "A1" },
  { dutch: "Ik kan Nederlands spreken.", english: "I can speak Dutch.", level: "A1" },
  { dutch: "Zij spreekt drie talen.", english: "She speaks three languages.", level: "A2" },
  { dutch: "Ik lees een boek.", english: "I am reading a book.", level: "A1" },
  { dutch: "Zij leest graag romans.", english: "She likes to read novels.", level: "A2" },
  { dutch: "Wij lezen de krant.", english: "We read the newspaper.", level: "A1" },
  { dutch: "Hij schrijft een brief.", english: "He writes a letter.", level: "A1" },
  { dutch: "Ik schrijf elke dag in mijn dagboek.", english: "I write in my diary every day.", level: "A2" },
  { dutch: "Luister naar de muziek.", english: "Listen to the music.", level: "A1" },
  { dutch: "Ik luister graag naar podcasts.", english: "I like listening to podcasts.", level: "A2" },
  { dutch: "Hij is een vriendelijk persoon.", english: "He is a friendly person.", level: "A1" },
  { dutch: "De buren zijn heel vriendelijk.", english: "The neighbors are very friendly.", level: "A2" },
  { dutch: "Amsterdam is een grote stad.", english: "Amsterdam is a big city.", level: "A1" },
  { dutch: "Het huis is te groot voor ons.", english: "The house is too big for us.", level: "A2" },
  { dutch: "Zij heeft een klein kind.", english: "She has a small child.", level: "A1" },
  { dutch: "Het is een klein probleem.", english: "It is a small problem.", level: "A2" },
  { dutch: "Wat een mooi uitzicht!", english: "What a beautiful view!", level: "A2" },
  { dutch: "Nederland is een mooi land.", english: "The Netherlands is a beautiful country.", level: "A1" },
  { dutch: "Het schilderij is heel mooi.", english: "The painting is very beautiful.", level: "B1" },
  { dutch: "Dat is een lelijk gebouw.", english: "That is an ugly building.", level: "A2" },
  { dutch: "Die auto is heel duur.", english: "That car is very expensive.", level: "A1" },
  { dutch: "Het leven in Amsterdam is duur.", english: "Life in Amsterdam is expensive.", level: "A2" },
  { dutch: "Ik ga met de auto naar het werk.", english: "I go to work by car.", level: "A2" },
  { dutch: "De auto is blauw.", english: "The car is blue.", level: "A1" },
  { dutch: "De trein vertrekt om acht uur.", english: "The train departs at eight o'clock.", level: "A2" },
  { dutch: "Ik neem de trein naar Utrecht.", english: "I take the train to Utrecht.", level: "A2" },
  { dutch: "De trein heeft vertraging.", english: "The train is delayed.", level: "A2" },
  { dutch: "Wij lopen door het bos.", english: "We walk through the forest.", level: "A2" },
  { dutch: "Ik loop elke ochtend.", english: "I walk every morning.", level: "A2" },
  { dutch: "Wat eet je vanavond?", english: "What are you eating tonight?", level: "A2" },
  { dutch: "Ik eet graag Italiaans.", english: "I like to eat Italian food.", level: "A2" },
  { dutch: "Zij eet geen vlees.", english: "She doesn't eat meat.", level: "A2" },
  { dutch: "Wil je iets drinken?", english: "Would you like something to drink?", level: "A1" },
  { dutch: "Ik drink koffie zonder suiker.", english: "I drink coffee without sugar.", level: "A2" },
  { dutch: "Mijn beste vriend woont in Rotterdam.", english: "My best friend lives in Rotterdam.", level: "A2" },
  { dutch: "Zij is een goede vriend van mij.", english: "She is a good friend of mine.", level: "A2" },
  { dutch: "Ik ga naar school.", english: "I go to school.", level: "A1" },
  { dutch: "De school begint om negen uur.", english: "School starts at nine o'clock.", level: "A2" },
  { dutch: "Ik moet morgen naar het werk.", english: "I have to go to work tomorrow.", level: "A2" },
  { dutch: "Zij zoekt nieuw werk.", english: "She is looking for new work.", level: "A2" },
  { dutch: "Den Haag is een mooie stad.", english: "The Hague is a beautiful city.", level: "A2" },
  { dutch: "Ik woon in de stad.", english: "I live in the city.", level: "A1" },
  { dutch: "Nederland is een klein land.", english: "The Netherlands is a small country.", level: "A1" },
  { dutch: "In welk land woon je?", english: "In which country do you live?", level: "A2" },
  { dutch: "De winkel is gesloten.", english: "The shop is closed.", level: "A2" },
  { dutch: "Ik ga naar de winkel.", english: "I go to the shop.", level: "A1" },
  { dutch: "Zij koopt nieuwe kleren.", english: "She buys new clothes.", level: "A2" },
  { dutch: "Ik reis graag naar Spanje.", english: "I like to travel to Spain.", level: "A2" },
  { dutch: "Wij reizen met het vliegtuig.", english: "We travel by airplane.", level: "A2" },
  { dutch: "Ik ben blij met het resultaat.", english: "I am happy with the result.", level: "A2" },
  { dutch: "Zij is heel blij.", english: "She is very happy.", level: "A1" },
  { dutch: "Ik ben moe na het werk.", english: "I am tired after work.", level: "A2" },
  { dutch: "Het was een moe dag.", english: "It was a tiring day.", level: "A2" },
  { dutch: "Het is gezellig in de woonkamer.", english: "It is cozy in the living room.", level: "A2" },
  { dutch: "We hadden een gezellig diner.", english: "We had a pleasant dinner.", level: "B1" },
  { dutch: "Het was gezellig op het feest.", english: "It was a fun party.", level: "A2" },
  { dutch: "Fijne vakantie!", english: "Have a nice holiday!", level: "A2" },
  { dutch: "Wij gaan op vakantie naar Frankrijk.", english: "We are going on holiday to France.", level: "A2" },
  { dutch: "Gezond eten is belangrijk.", english: "Healthy eating is important.", level: "A2" },
  { dutch: "Hij leeft gezond.", english: "He lives healthily.", level: "A2" },
  { dutch: "Het huis is schoon.", english: "The house is clean.", level: "A1" },
  { dutch: "Ik maak de keuken schoon.", english: "I clean the kitchen.", level: "A2" },

  { dutch: "Ik begrijp de vraag niet.", english: "I don't understand the question.", level: "B1" },
  { dutch: "Begrijp je wat ik bedoel?", english: "Do you understand what I mean?", level: "B1" },
  { dutch: "Het is moeilijk te begrijpen.", english: "It is difficult to understand.", level: "B1" },
  { dutch: "Ik wil het graag proberen.", english: "I would like to try it.", level: "B1" },
  { dutch: "Probeer het nog een keer.", english: "Try it one more time.", level: "B1" },
  { dutch: "Zij probeert een nieuwe baan te vinden.", english: "She is trying to find a new job.", level: "B1" },
  { dutch: "Ik geloof dat het waar is.", english: "I believe it is true.", level: "B1" },
  { dutch: "Geloof je in wonderen?", english: "Do you believe in miracles?", level: "B1" },
  { dutch: "Ik ben mijn sleutels vergeten.", english: "I forgot my keys.", level: "B1" },
  { dutch: "Vergeet niet om melk te kopen.", english: "Don't forget to buy milk.", level: "B1" },
  { dutch: "Zij is haar afspraak vergeten.", english: "She forgot her appointment.", level: "B1" },
  { dutch: "Ik kan het me niet herinneren.", english: "I cannot remember it.", level: "B1" },
  { dutch: "Probeer het te onthouden.", english: "Try to remember it.", level: "B1" },
  { dutch: "Hij heeft veel ervaring.", english: "He has a lot of experience.", level: "B1" },
  { dutch: "Dat was een goede ervaring.", english: "That was a good experience.", level: "B1" },
  { dutch: "Het is een moeilijke beslissing.", english: "It is a difficult decision.", level: "B1" },
  { dutch: "We moeten een beslissing nemen.", english: "We have to make a decision.", level: "B1" },
  { dutch: "Gezondheid is het belangrijkste.", english: "Health is the most important thing.", level: "B1" },
  { dutch: "Hij maakt zich zorgen over zijn gezondheid.", english: "He is worried about his health.", level: "B1" },
  { dutch: "Het onderwijs in Nederland is goed.", english: "Education in the Netherlands is good.", level: "B1" },
  { dutch: "Zij werkt in het onderwijs.", english: "She works in education.", level: "B1" },
  { dutch: "Het is een grote verantwoordelijkheid.", english: "It is a big responsibility.", level: "B1" },
  { dutch: "We moeten een oplossing vinden.", english: "We need to find a solution.", level: "B1" },
  { dutch: "Er is geen eenvoudige oplossing.", english: "There is no simple solution.", level: "B1" },
  { dutch: "Je hebt mijn toestemming.", english: "You have my permission.", level: "B1" },
  { dutch: "We moeten ons Nederlands verbeteren.", english: "We need to improve our Dutch.", level: "B1" },
  { dutch: "De situatie is verbeterd.", english: "The situation has improved.", level: "B1" },
  { dutch: "Culturen kunnen van elkaar verschillen.", english: "Cultures can differ from each other.", level: "B1" },
  { dutch: "Kun je dat beter verklaren?", english: "Can you explain that better?", level: "B1" },
  { dutch: "De politie heeft het incident verklaard.", english: "The police explained the incident.", level: "B1" },
  { dutch: "Het weer is vandaag heel mooi.", english: "The weather is very nice today.", level: "A1" },
  { dutch: "Ik hou van Nederland.", english: "I love the Netherlands.", level: "A1" },
  { dutch: "Waar is het station?", english: "Where is the station?", level: "A1" },
  { dutch: "Het station is dichtbij.", english: "The station is nearby.", level: "A1" },
  { dutch: "Ik kom uit Rusland.", english: "I come from Russia.", level: "A1" },
  { dutch: "Hoe laat is het?", english: "What time is it?", level: "A1" },
  { dutch: "Het is drie uur.", english: "It is three o'clock.", level: "A1" },
  { dutch: "Ik ga naar de supermarkt.", english: "I go to the supermarket.", level: "A1" },
  { dutch: "De supermarkt is open tot tien uur.", english: "The supermarket is open until ten o'clock.", level: "A2" },
  { dutch: "Zij heeft twee kinderen.", english: "She has two children.", level: "A1" },
  { dutch: "De kinderen spelen buiten.", english: "The children play outside.", level: "A1" },
  { dutch: "Het restaurant is heel goed.", english: "The restaurant is very good.", level: "A2" },
  { dutch: "Wij eten in een restaurant.", english: "We eat at a restaurant.", level: "A2" },
  { dutch: "Ik heb een afspraak bij de dokter.", english: "I have an appointment at the doctor.", level: "A2" },
  { dutch: "De dokter zegt dat ik gezond ben.", english: "The doctor says I am healthy.", level: "A2" },
  { dutch: "Het museum is erg interessant.", english: "The museum is very interesting.", level: "A2" },
  { dutch: "Wij bezoeken het museum.", english: "We visit the museum.", level: "A2" },
  { dutch: "De bibliotheek is dicht.", english: "The library is closed.", level: "A2" },
  { dutch: "Ik leen boeken van de bibliotheek.", english: "I borrow books from the library.", level: "A2" },
  { dutch: "Hoeveel kost dit?", english: "How much does this cost?", level: "A1" },
  { dutch: "Dat kost vijf euro.", english: "That costs five euros.", level: "A1" },
  { dutch: "Ik betaal met mijn pinpas.", english: "I pay with my debit card.", level: "A2" },

  { dutch: "Het is een grote uitdaging.", english: "It is a big challenge.", level: "B2" },
  { dutch: "Zij ziet het als een uitdaging.", english: "She sees it as a challenge.", level: "B2" },
  { dutch: "De technologische ontwikkeling gaat snel.", english: "Technological development is progressing quickly.", level: "B2" },
  { dutch: "De ontwikkeling van het project verloopt goed.", english: "The development of the project is going well.", level: "B2" },
  { dutch: "Zij is een onafhankelijk persoon.", english: "She is an independent person.", level: "B2" },
  { dutch: "Het land werd onafhankelijk in 1945.", english: "The country became independent in 1945.", level: "B2" },
  { dutch: "De maatschappij verandert snel.", english: "Society is changing quickly.", level: "B2" },
  { dutch: "Wij leven in een diverse maatschappij.", english: "We live in a diverse society.", level: "B2" },
  { dutch: "Duurzaamheid is belangrijk voor de toekomst.", english: "Sustainability is important for the future.", level: "B2" },
  { dutch: "Het bedrijf investeert in duurzaamheid.", english: "The company invests in sustainability.", level: "B2" },
  { dutch: "Hij probeert mij te overtuigen.", english: "He is trying to convince me.", level: "B2" },
  { dutch: "Zij kon de jury overtuigen.", english: "She was able to convince the jury.", level: "B2" },
  { dutch: "De media heeft veel invloed.", english: "The media has a lot of influence.", level: "B2" },
  { dutch: "Sociale media heeft invloed op jongeren.", english: "Social media has an influence on young people.", level: "B2" },
  { dutch: "Het probleem is ingewikkeld.", english: "The problem is complicated.", level: "B2" },
  { dutch: "De situatie wordt steeds ingewikkelder.", english: "The situation is becoming increasingly complicated.", level: "B2" },
  { dutch: "De toekomst ziet er goed uit.", english: "The future looks good.", level: "B2" },
  { dutch: "Wij denken aan de toekomst.", english: "We think about the future.", level: "B1" },
  { dutch: "Er zijn veel mogelijkheden.", english: "There are many possibilities.", level: "B2" },
  { dutch: "Dit is de enige mogelijkheid.", english: "This is the only possibility.", level: "B2" },
  { dutch: "Het is een uitzondering op de regel.", english: "It is an exception to the rule.", level: "B2" },
  { dutch: "Ik moet me voorbereiden op het examen.", english: "I have to prepare for the exam.", level: "B2" },
  { dutch: "Zij bereidt het diner voor.", english: "She is preparing dinner.", level: "B1" },
  { dutch: "Je kunt de prijzen vergelijken.", english: "You can compare the prices.", level: "B2" },
  { dutch: "Het is moeilijk om te vergelijken.", english: "It is difficult to compare.", level: "B2" },
  { dutch: "We moeten dit probleem voorkomen.", english: "We have to prevent this problem.", level: "B2" },
  { dutch: "Hoe kunnen we ongelukken voorkomen?", english: "How can we prevent accidents?", level: "B2" },
  { dutch: "De omgeving is heel groen.", english: "The environment is very green.", level: "B2" },
  { dutch: "Wij moeten de omgeving beschermen.", english: "We must protect the environment.", level: "B2" },

  { dutch: "Ik wil Nederlands leren.", english: "I want to learn Dutch.", level: "A1" },
  { dutch: "Het leren van een taal kost tijd.", english: "Learning a language takes time.", level: "A2" },
  { dutch: "Zij studeert aan de universiteit.", english: "She studies at the university.", level: "A2" },
  { dutch: "De universiteit is in Leiden.", english: "The university is in Leiden.", level: "A2" },
  { dutch: "Ik heb een vraag.", english: "I have a question.", level: "A1" },
  { dutch: "Mag ik een vraag stellen?", english: "May I ask a question?", level: "A2" },
  { dutch: "Het antwoord is ja.", english: "The answer is yes.", level: "A1" },
  { dutch: "Ik weet het antwoord niet.", english: "I don't know the answer.", level: "A1" },
  { dutch: "De les begint om tien uur.", english: "The lesson starts at ten o'clock.", level: "A2" },
  { dutch: "Vandaag hebben we een nieuwe les.", english: "Today we have a new lesson.", level: "A2" },
  { dutch: "Mijn familie woont in Amsterdam.", english: "My family lives in Amsterdam.", level: "A1" },
  { dutch: "Familie is heel belangrijk.", english: "Family is very important.", level: "A2" },
  { dutch: "Mijn broer is ouder dan ik.", english: "My brother is older than me.", level: "A2" },
  { dutch: "Mijn zus woont in Den Haag.", english: "My sister lives in The Hague.", level: "A2" },
  { dutch: "Mijn ouders komen uit Turkije.", english: "My parents come from Turkey.", level: "A2" },
  { dutch: "Ik heb twee broers en een zus.", english: "I have two brothers and one sister.", level: "A1" },
  { dutch: "De tafel staat in de keuken.", english: "The table is in the kitchen.", level: "A1" },
  { dutch: "Wij zitten aan tafel.", english: "We sit at the table.", level: "A1" },
  { dutch: "De stoel is kapot.", english: "The chair is broken.", level: "A1" },
  { dutch: "Doe de deur dicht.", english: "Close the door.", level: "A1" },
  { dutch: "Het raam is open.", english: "The window is open.", level: "A1" },
  { dutch: "De zon schijnt vandaag.", english: "The sun is shining today.", level: "A1" },
  { dutch: "Het regent buiten.", english: "It is raining outside.", level: "A1" },
  { dutch: "Het sneeuwt in de winter.", english: "It snows in winter.", level: "A2" },
  { dutch: "De zomer is mijn favoriete seizoen.", english: "Summer is my favorite season.", level: "A2" },
  { dutch: "In de herfst vallen de bladeren.", english: "In autumn the leaves fall.", level: "A2" },
  { dutch: "De lente begint in maart.", english: "Spring starts in March.", level: "A2" },
  { dutch: "Ik hou van koken.", english: "I love cooking.", level: "A2" },
  { dutch: "Zij kookt elke avond.", english: "She cooks every evening.", level: "A2" },
  { dutch: "Het eten smaakt lekker.", english: "The food tastes good.", level: "A1" },
  { dutch: "Dit is een lekker recept.", english: "This is a good recipe.", level: "A2" },
  { dutch: "Ik drink thee met honing.", english: "I drink tea with honey.", level: "A1" },
  { dutch: "Wil je koffie of thee?", english: "Would you like coffee or tea?", level: "A1" },
  { dutch: "De koffie is heet.", english: "The coffee is hot.", level: "A1" },
  { dutch: "Ik neem een kopje koffie.", english: "I'll have a cup of coffee.", level: "A1" },
  { dutch: "Zij werkt in een ziekenhuis.", english: "She works in a hospital.", level: "A2" },
  { dutch: "Het ziekenhuis is in het centrum.", english: "The hospital is in the center.", level: "A2" },
  { dutch: "De politie komt eraan.", english: "The police are coming.", level: "A2" },
  { dutch: "Bel de politie!", english: "Call the police!", level: "A2" },
  { dutch: "Ik zoek een baan.", english: "I am looking for a job.", level: "A2" },
  { dutch: "Hij heeft een nieuwe baan gevonden.", english: "He found a new job.", level: "B1" },
  { dutch: "Het salaris is goed.", english: "The salary is good.", level: "B1" },
  { dutch: "Zij heeft een vergadering om twee uur.", english: "She has a meeting at two o'clock.", level: "B1" },
  { dutch: "De vergadering duurde drie uur.", english: "The meeting lasted three hours.", level: "B1" },
  { dutch: "Ik stuur je een e-mail.", english: "I will send you an email.", level: "A2" },
  { dutch: "Heb je mijn e-mail ontvangen?", english: "Did you receive my email?", level: "A2" },
  { dutch: "De telefoon gaat.", english: "The phone is ringing.", level: "A1" },
  { dutch: "Ik bel je morgen.", english: "I will call you tomorrow.", level: "A2" },
  { dutch: "Het internet werkt niet.", english: "The internet is not working.", level: "A2" },
  { dutch: "De computer is langzaam.", english: "The computer is slow.", level: "A2" },

  { dutch: "Zij heeft een belangrijke rol in het bedrijf.", english: "She has an important role in the company.", level: "B1" },
  { dutch: "Het bedrijf groeit snel.", english: "The company is growing quickly.", level: "B1" },
  { dutch: "De economie is sterk dit jaar.", english: "The economy is strong this year.", level: "B2" },
  { dutch: "De regering neemt nieuwe maatregelen.", english: "The government is taking new measures.", level: "B2" },
  { dutch: "Het is belangrijk om te stemmen.", english: "It is important to vote.", level: "B1" },
  { dutch: "De wet beschermt de consument.", english: "The law protects the consumer.", level: "B2" },
  { dutch: "Iedereen heeft recht op onderwijs.", english: "Everyone has the right to education.", level: "B1" },
  { dutch: "De rechter heeft een besluit genomen.", english: "The judge has made a decision.", level: "B2" },
  { dutch: "Wij geloven in gelijkheid.", english: "We believe in equality.", level: "B1" },
  { dutch: "Het klimaat verandert door de mens.", english: "The climate is changing because of humans.", level: "B2" },
  { dutch: "Wij moeten energie besparen.", english: "We must save energy.", level: "B1" },
  { dutch: "Zonne-energie is de toekomst.", english: "Solar energy is the future.", level: "B2" },
  { dutch: "Het verkeer is druk in de ochtend.", english: "Traffic is busy in the morning.", level: "A2" },
  { dutch: "Er was een ongeluk op de snelweg.", english: "There was an accident on the highway.", level: "B1" },
  { dutch: "De bus komt om het kwartier.", english: "The bus comes every quarter hour.", level: "A2" },
  { dutch: "Ik neem de bus naar huis.", english: "I take the bus home.", level: "A1" },
  { dutch: "Het vliegtuig vertrekt om zes uur.", english: "The plane departs at six o'clock.", level: "A2" },
  { dutch: "De vlucht duurt twee uur.", english: "The flight takes two hours.", level: "A2" },
  { dutch: "Het hotel is comfortabel.", english: "The hotel is comfortable.", level: "A2" },
  { dutch: "Wij logeren in een hotel.", english: "We stay in a hotel.", level: "A2" },
  { dutch: "De haven van Rotterdam is de grootste van Europa.", english: "The port of Rotterdam is the largest in Europe.", level: "B1" },
  { dutch: "De tulpen bloeien in het voorjaar.", english: "The tulips bloom in spring.", level: "A2" },
  { dutch: "Nederland staat bekend om zijn tulpen.", english: "The Netherlands is known for its tulips.", level: "A2" },
  { dutch: "De molen staat aan het water.", english: "The windmill stands by the water.", level: "A2" },
  { dutch: "Er zijn veel fietspaden in Nederland.", english: "There are many bicycle paths in the Netherlands.", level: "A2" },
  { dutch: "Ik sport drie keer per week.", english: "I exercise three times a week.", level: "A2" },
  { dutch: "Voetbal is populair in Nederland.", english: "Football is popular in the Netherlands.", level: "A2" },
  { dutch: "Hij speelt voetbal in een team.", english: "He plays football on a team.", level: "A2" },
  { dutch: "Zwemmen is goed voor je gezondheid.", english: "Swimming is good for your health.", level: "B1" },
  { dutch: "Ik ga graag hardlopen.", english: "I like to go running.", level: "A2" },
  { dutch: "De film was heel spannend.", english: "The movie was very exciting.", level: "A2" },
  { dutch: "Wij gaan naar de bioscoop.", english: "We are going to the cinema.", level: "A2" },
  { dutch: "Het concert begint om acht uur.", english: "The concert starts at eight o'clock.", level: "A2" },
  { dutch: "Zij speelt piano.", english: "She plays piano.", level: "A2" },
  { dutch: "Ik luister graag naar klassieke muziek.", english: "I enjoy listening to classical music.", level: "B1" },
  { dutch: "Kunst is een vorm van expressie.", english: "Art is a form of expression.", level: "B1" },
  { dutch: "Het schilderij hangt in het Rijksmuseum.", english: "The painting hangs in the Rijksmuseum.", level: "B1" },

  { dutch: "Ik voel me vandaag niet lekker.", english: "I don't feel well today.", level: "A2" },
  { dutch: "Hij is verkouden.", english: "He has a cold.", level: "A2" },
  { dutch: "Ik heb hoofdpijn.", english: "I have a headache.", level: "A1" },
  { dutch: "De apotheek is om de hoek.", english: "The pharmacy is around the corner.", level: "A2" },
  { dutch: "Ik moet medicijnen nemen.", english: "I have to take medicine.", level: "A2" },
  { dutch: "Het is belangrijk om genoeg te slapen.", english: "It is important to sleep enough.", level: "A2" },
  { dutch: "Ik ben allergisch voor noten.", english: "I am allergic to nuts.", level: "A2" },
  { dutch: "Waar is de dichtstbijzijnde apotheek?", english: "Where is the nearest pharmacy?", level: "A2" },
  { dutch: "De verjaardag van mijn moeder is morgen.", english: "My mother's birthday is tomorrow.", level: "A2" },
  { dutch: "Gefeliciteerd met je verjaardag!", english: "Happy birthday!", level: "A1" },
  { dutch: "Wij vieren Kerstmis met de familie.", english: "We celebrate Christmas with the family.", level: "A2" },
  { dutch: "Koningsdag is op 27 april.", english: "King's Day is on April 27th.", level: "A2" },
  { dutch: "Sinterklaas is een Nederlandse traditie.", english: "Sinterklaas is a Dutch tradition.", level: "A2" },
  { dutch: "Het is een mooie traditie.", english: "It is a beautiful tradition.", level: "A2" },
  { dutch: "Ik heb een afspraak met de tandarts.", english: "I have an appointment with the dentist.", level: "A2" },
  { dutch: "De tandarts zegt dat alles goed is.", english: "The dentist says everything is fine.", level: "A2" },
  { dutch: "Ik moet een formulier invullen.", english: "I have to fill out a form.", level: "B1" },
  { dutch: "Waar moet ik tekenen?", english: "Where do I sign?", level: "B1" },
  { dutch: "Het contract is voor twee jaar.", english: "The contract is for two years.", level: "B1" },
  { dutch: "Ik heb een verzekering nodig.", english: "I need insurance.", level: "B1" },
  { dutch: "De huur is vijfhonderd euro per maand.", english: "The rent is five hundred euros per month.", level: "B1" },
  { dutch: "Wij verhuizen naar een ander huis.", english: "We are moving to a different house.", level: "B1" },
  { dutch: "De buurt is heel rustig.", english: "The neighborhood is very quiet.", level: "A2" },
  { dutch: "Er is een park in de buurt.", english: "There is a park in the neighborhood.", level: "A2" },
  { dutch: "Het park is groot en groen.", english: "The park is big and green.", level: "A1" },
  { dutch: "De vogels zingen in de bomen.", english: "The birds sing in the trees.", level: "A2" },
  { dutch: "De bloemen ruiken lekker.", english: "The flowers smell nice.", level: "A2" },
  { dutch: "De tuin is vol met bloemen.", english: "The garden is full of flowers.", level: "A2" },
];
