export interface SeedWord {
  dutch: string;
  translationRu: string;
  translationEn: string;
  translationUk: string;
  level: string;
  translation: string;
  knownCount: number;
  isLearned: boolean;
  isUserAdded: boolean;
}

function w(dutch: string, ru: string, en: string, uk: string, level: string): SeedWord {
  return {
    dutch,
    translationRu: ru,
    translationEn: en,
    translationUk: uk,
    level,
    translation: `${ru} / ${en}`,
    knownCount: 0,
    isLearned: false,
    isUserAdded: false,
  };
}

export const SEED_WORDS: SeedWord[] = [
  // ===== A1 - BASIC VOCABULARY =====
  // Greetings
  w("Hallo", "Привет", "Hello", "Привіт", "A1"),
  w("Dag", "До свидания", "Goodbye", "До побачення", "A1"),
  w("Goedemorgen", "Доброе утро", "Good morning", "Доброго ранку", "A1"),
  w("Goedemiddag", "Добрый день", "Good afternoon", "Доброго дня", "A1"),
  w("Goedenavond", "Добрый вечер", "Good evening", "Доброго вечора", "A1"),
  w("Goedenacht", "Спокойной ночи", "Good night", "На добраніч", "A1"),
  w("Ja", "Да", "Yes", "Так", "A1"),
  w("Nee", "Нет", "No", "Ні", "A1"),
  w("Dank u", "Спасибо", "Thank you", "Дякую", "A1"),
  w("Alstublieft", "Пожалуйста", "Please", "Будь ласка", "A1"),
  w("Sorry", "Извините", "Sorry", "Вибачте", "A1"),
  w("Pardon", "Простите", "Pardon", "Перепрошую", "A1"),
  w("Tot ziens", "До свидания", "See you", "До зустрічі", "A1"),
  w("Welkom", "Добро пожаловать", "Welcome", "Ласкаво просимо", "A1"),
  w("Doei", "Пока", "Bye", "Бувай", "A1"),
  w("Welterusten", "Спокойной ночи", "Good night", "На добраніч", "A1"),
  w("Smakelijk", "Приятного аппетита", "Enjoy your meal", "Смачного", "A1"),
  w("Proost", "За здоровье", "Cheers", "Будьмо", "A1"),
  w("Gefeliciteerd", "Поздравляю", "Congratulations", "Вітаю", "A1"),
  // Numbers
  w("Een", "Один", "One", "Один", "A1"),
  w("Twee", "Два", "Two", "Два", "A1"),
  w("Drie", "Три", "Three", "Три", "A1"),
  w("Vier", "Четыре", "Four", "Чотири", "A1"),
  w("Vijf", "Пять", "Five", "П'ять", "A1"),
  w("Zes", "Шесть", "Six", "Шість", "A1"),
  w("Zeven", "Семь", "Seven", "Сім", "A1"),
  w("Acht", "Восемь", "Eight", "Вісім", "A1"),
  w("Negen", "Девять", "Nine", "Дев'ять", "A1"),
  w("Tien", "Десять", "Ten", "Десять", "A1"),
  w("Elf", "Одиннадцать", "Eleven", "Одинадцять", "A1"),
  w("Twaalf", "Двенадцать", "Twelve", "Дванадцять", "A1"),
  w("Dertien", "Тринадцать", "Thirteen", "Тринадцять", "A1"),
  w("Veertien", "Четырнадцать", "Fourteen", "Чотирнадцять", "A1"),
  w("Vijftien", "Пятнадцать", "Fifteen", "П'ятнадцять", "A1"),
  w("Zestien", "Шестнадцать", "Sixteen", "Шістнадцять", "A1"),
  w("Zeventien", "Семнадцать", "Seventeen", "Сімнадцять", "A1"),
  w("Achttien", "Восемнадцать", "Eighteen", "Вісімнадцять", "A1"),
  w("Negentien", "Девятнадцать", "Nineteen", "Дев'ятнадцять", "A1"),
  w("Twintig", "Двадцать", "Twenty", "Двадцять", "A1"),
  w("Dertig", "Тридцать", "Thirty", "Тридцять", "A1"),
  w("Veertig", "Сорок", "Forty", "Сорок", "A1"),
  w("Vijftig", "Пятьдесят", "Fifty", "П'ятдесят", "A1"),
  w("Zestig", "Шестьдесят", "Sixty", "Шістдесят", "A1"),
  w("Zeventig", "Семьдесят", "Seventy", "Сімдесят", "A1"),
  w("Tachtig", "Восемьдесят", "Eighty", "Вісімдесят", "A1"),
  w("Negentig", "Девяносто", "Ninety", "Дев'яносто", "A1"),
  w("Honderd", "Сто", "Hundred", "Сто", "A1"),
  w("Duizend", "Тысяча", "Thousand", "Тисяча", "A1"),
  // Colors
  w("Rood", "Красный", "Red", "Червоний", "A1"),
  w("Blauw", "Синий", "Blue", "Синій", "A1"),
  w("Groen", "Зелёный", "Green", "Зелений", "A1"),
  w("Geel", "Жёлтый", "Yellow", "Жовтий", "A1"),
  w("Wit", "Белый", "White", "Білий", "A1"),
  w("Zwart", "Чёрный", "Black", "Чорний", "A1"),
  w("Grijs", "Серый", "Grey", "Сірий", "A1"),
  w("Bruin", "Коричневый", "Brown", "Коричневий", "A1"),
  w("Roze", "Розовый", "Pink", "Рожевий", "A1"),
  w("Oranje", "Оранжевый", "Orange", "Помаранчевий", "A1"),
  w("Paars", "Фиолетовый", "Purple", "Фіолетовий", "A1"),
  // Family
  w("Vader", "Отец", "Father", "Батько", "A1"),
  w("Moeder", "Мать", "Mother", "Мати", "A1"),
  w("Broer", "Брат", "Brother", "Брат", "A1"),
  w("Zus", "Сестра", "Sister", "Сестра", "A1"),
  w("Zoon", "Сын", "Son", "Син", "A1"),
  w("Dochter", "Дочь", "Daughter", "Дочка", "A1"),
  w("Opa", "Дедушка", "Grandfather", "Дідусь", "A1"),
  w("Oma", "Бабушка", "Grandmother", "Бабуся", "A1"),
  w("Oom", "Дядя", "Uncle", "Дядько", "A1"),
  w("Tante", "Тётя", "Aunt", "Тітка", "A1"),
  w("Neef", "Племянник/кузен", "Nephew/Cousin", "Небіж/кузен", "A1"),
  w("Nicht", "Племянница/кузина", "Niece/Cousin", "Небога/кузина", "A1"),
  w("Man", "Мужчина/муж", "Man/Husband", "Чоловік", "A1"),
  w("Vrouw", "Женщина/жена", "Woman/Wife", "Жінка", "A1"),
  w("Kind", "Ребёнок", "Child", "Дитина", "A1"),
  w("Baby", "Малыш", "Baby", "Немовля", "A1"),
  w("Jongen", "Мальчик", "Boy", "Хлопчик", "A1"),
  w("Meisje", "Девочка", "Girl", "Дівчинка", "A1"),
  w("Familie", "Семья", "Family", "Сім'я", "A1"),
  w("Ouders", "Родители", "Parents", "Батьки", "A1"),
  // Animals
  w("Hond", "Собака", "Dog", "Собака", "A1"),
  w("Kat", "Кошка", "Cat", "Кішка", "A1"),
  w("Vis", "Рыба", "Fish", "Риба", "A1"),
  w("Vogel", "Птица", "Bird", "Птах", "A1"),
  w("Paard", "Лошадь", "Horse", "Кінь", "A1"),
  w("Koe", "Корова", "Cow", "Корова", "A1"),
  w("Varken", "Свинья", "Pig", "Свиня", "A1"),
  w("Schaap", "Овца", "Sheep", "Вівця", "A1"),
  w("Kip", "Курица", "Chicken", "Курка", "A1"),
  w("Konijn", "Кролик", "Rabbit", "Кролик", "A1"),
  w("Muis", "Мышь", "Mouse", "Миша", "A1"),
  w("Eend", "Утка", "Duck", "Качка", "A1"),
  w("Beer", "Медведь", "Bear", "Ведмідь", "A1"),
  w("Leeuw", "Лев", "Lion", "Лев", "A1"),
  w("Olifant", "Слон", "Elephant", "Слон", "A1"),
  w("Aap", "Обезьяна", "Monkey", "Мавпа", "A1"),
  w("Slang", "Змея", "Snake", "Змія", "A1"),
  w("Spin", "Паук", "Spider", "Павук", "A1"),
  w("Vlinder", "Бабочка", "Butterfly", "Метелик", "A1"),
  w("Bij", "Пчела", "Bee", "Бджола", "A1"),
  w("Geit", "Коза", "Goat", "Коза", "A1"),
  w("Hert", "Олень", "Deer", "Олень", "A1"),
  w("Vos", "Лиса", "Fox", "Лисиця", "A1"),
  w("Wolf", "Волк", "Wolf", "Вовк", "A1"),
  w("Uil", "Сова", "Owl", "Сова", "A1"),
  w("Papegaai", "Попугай", "Parrot", "Папуга", "A1"),
  w("Schildpad", "Черепаха", "Turtle", "Черепаха", "A1"),
  w("Kikker", "Лягушка", "Frog", "Жаба", "A1"),
  w("Krokodil", "Крокодил", "Crocodile", "Крокодил", "A1"),
  w("Tijger", "Тигр", "Tiger", "Тигр", "A1"),
  w("Dolfijn", "Дельфин", "Dolphin", "Дельфін", "A1"),
  w("Walvis", "Кит", "Whale", "Кит", "A1"),
  w("Haai", "Акула", "Shark", "Акула", "A1"),
  w("Zebra", "Зебра", "Zebra", "Зебра", "A1"),
  w("Giraf", "Жираф", "Giraffe", "Жирафа", "A1"),
  w("Mier", "Муравей", "Ant", "Мураха", "A1"),
  w("Vlieg", "Муха", "Fly", "Муха", "A1"),
  w("Mug", "Комар", "Mosquito", "Комар", "A1"),
  w("Worm", "Червь", "Worm", "Черв'як", "A1"),
  w("Slak", "Улитка", "Snail", "Равлик", "A1"),
  // Food & Drink
  w("Brood", "Хлеб", "Bread", "Хліб", "A1"),
  w("Water", "Вода", "Water", "Вода", "A1"),
  w("Kaas", "Сыр", "Cheese", "Сир", "A1"),
  w("Melk", "Молоко", "Milk", "Молоко", "A1"),
  w("Appel", "Яблоко", "Apple", "Яблуко", "A1"),
  w("Banaan", "Банан", "Banana", "Банан", "A1"),
  w("Ei", "Яйцо", "Egg", "Яйце", "A1"),
  w("Rijst", "Рис", "Rice", "Рис", "A1"),
  w("Vlees", "Мясо", "Meat", "М'ясо", "A1"),
  w("Soep", "Суп", "Soup", "Суп", "A1"),
  w("Salade", "Салат", "Salad", "Салат", "A1"),
  w("Boter", "Масло", "Butter", "Масло", "A1"),
  w("Suiker", "Сахар", "Sugar", "Цукор", "A1"),
  w("Zout", "Соль", "Salt", "Сіль", "A1"),
  w("Peper", "Перец", "Pepper", "Перець", "A1"),
  w("Thee", "Чай", "Tea", "Чай", "A1"),
  w("Koffie", "Кофе", "Coffee", "Кава", "A1"),
  w("Sap", "Сок", "Juice", "Сік", "A1"),
  w("Bier", "Пиво", "Beer", "Пиво", "A1"),
  w("Wijn", "Вино", "Wine", "Вино", "A1"),
  w("Aardappel", "Картофель", "Potato", "Картопля", "A1"),
  w("Wortel", "Морковь", "Carrot", "Морква", "A1"),
  w("Tomaat", "Помидор", "Tomato", "Помідор", "A1"),
  w("Ui", "Лук", "Onion", "Цибуля", "A1"),
  w("Komkommer", "Огурец", "Cucumber", "Огірок", "A1"),
  w("Sinaasappel", "Апельсин", "Orange", "Апельсин", "A1"),
  w("Citroen", "Лимон", "Lemon", "Лимон", "A1"),
  w("Druif", "Виноград", "Grape", "Виноград", "A1"),
  w("Peer", "Груша", "Pear", "Груша", "A1"),
  w("Kers", "Вишня", "Cherry", "Вишня", "A1"),
  w("Aardbei", "Клубника", "Strawberry", "Полуниця", "A1"),
  w("Noot", "Орех", "Nut", "Горіх", "A1"),
  w("Chocolade", "Шоколад", "Chocolate", "Шоколад", "A1"),
  w("Taart", "Торт", "Cake", "Торт", "A1"),
  w("IJs", "Мороженое", "Ice cream", "Морозиво", "A1"),
  w("Snoep", "Конфеты", "Candy", "Цукерки", "A1"),
  w("Pannenkoek", "Блин", "Pancake", "Млинець", "A1"),
  w("Friet", "Картофель фри", "French fries", "Картопля фрі", "A1"),
  w("Gehakt", "Фарш", "Minced meat", "Фарш", "A1"),
  w("Worst", "Колбаса", "Sausage", "Ковбаса", "A1"),
  w("Ham", "Ветчина", "Ham", "Шинка", "A1"),
  w("Honing", "Мёд", "Honey", "Мед", "A1"),
  w("Olie", "Масло (растит.)", "Oil", "Олія", "A1"),
  w("Meel", "Мука", "Flour", "Борошно", "A1"),
  w("Room", "Сливки", "Cream", "Вершки", "A1"),
  w("Yoghurt", "Йогурт", "Yogurt", "Йогурт", "A1"),
  // House
  w("Huis", "Дом", "House", "Дім", "A1"),
  w("Kamer", "Комната", "Room", "Кімната", "A1"),
  w("Keuken", "Кухня", "Kitchen", "Кухня", "A1"),
  w("Slaapkamer", "Спальня", "Bedroom", "Спальня", "A1"),
  w("Badkamer", "Ванная", "Bathroom", "Ванна кімната", "A1"),
  w("Woonkamer", "Гостиная", "Living room", "Вітальня", "A1"),
  w("Tuin", "Сад", "Garden", "Сад", "A1"),
  w("Deur", "Дверь", "Door", "Двері", "A1"),
  w("Raam", "Окно", "Window", "Вікно", "A1"),
  w("Tafel", "Стол", "Table", "Стіл", "A1"),
  w("Stoel", "Стул", "Chair", "Стілець", "A1"),
  w("Bed", "Кровать", "Bed", "Ліжко", "A1"),
  w("Bank", "Диван", "Sofa", "Диван", "A1"),
  w("Lamp", "Лампа", "Lamp", "Лампа", "A1"),
  w("Trap", "Лестница", "Stairs", "Сходи", "A1"),
  w("Vloer", "Пол", "Floor", "Підлога", "A1"),
  w("Muur", "Стена", "Wall", "Стіна", "A1"),
  w("Plafond", "Потолок", "Ceiling", "Стеля", "A1"),
  w("Dak", "Крыша", "Roof", "Дах", "A1"),
  w("Balkon", "Балкон", "Balcony", "Балкон", "A1"),
  w("Garage", "Гараж", "Garage", "Гараж", "A1"),
  w("Kelder", "Подвал", "Basement", "Підвал", "A1"),
  w("Zolder", "Чердак", "Attic", "Горище", "A1"),
  w("Kussen", "Подушка", "Pillow", "Подушка", "A1"),
  w("Deken", "Одеяло", "Blanket", "Ковдра", "A1"),
  w("Gordijn", "Штора", "Curtain", "Штора", "A1"),
  w("Tapijt", "Ковёр", "Carpet", "Килим", "A1"),
  w("Kast", "Шкаф", "Cupboard", "Шафа", "A1"),
  w("Fornuis", "Плита", "Stove", "Плита", "A1"),
  w("Toilet", "Туалет", "Toilet", "Туалет", "A1"),
  w("Bad", "Ванна", "Bath", "Ванна", "A1"),
  // Body
  w("Hoofd", "Голова", "Head", "Голова", "A1"),
  w("Haar", "Волосы", "Hair", "Волосся", "A1"),
  w("Oog", "Глаз", "Eye", "Око", "A1"),
  w("Oor", "Ухо", "Ear", "Вухо", "A1"),
  w("Neus", "Нос", "Nose", "Ніс", "A1"),
  w("Mond", "Рот", "Mouth", "Рот", "A1"),
  w("Tand", "Зуб", "Tooth", "Зуб", "A1"),
  w("Tong", "Язык", "Tongue", "Язик", "A1"),
  w("Nek", "Шея", "Neck", "Шия", "A1"),
  w("Schouder", "Плечо", "Shoulder", "Плече", "A1"),
  w("Arm", "Рука (от плеча)", "Arm", "Рука", "A1"),
  w("Hand", "Кисть руки", "Hand", "Кисть руки", "A1"),
  w("Vinger", "Палец руки", "Finger", "Палець руки", "A1"),
  w("Been", "Нога", "Leg", "Нога", "A1"),
  w("Voet", "Стопа", "Foot", "Стопа", "A1"),
  w("Knie", "Колено", "Knee", "Коліно", "A1"),
  w("Rug", "Спина", "Back", "Спина", "A1"),
  w("Buik", "Живот", "Belly", "Живіт", "A1"),
  w("Hart", "Сердце", "Heart", "Серце", "A1"),
  w("Huid", "Кожа", "Skin", "Шкіра", "A1"),
  // Clothes
  w("Broek", "Брюки", "Pants", "Штани", "A1"),
  w("Shirt", "Рубашка", "Shirt", "Сорочка", "A1"),
  w("Jas", "Куртка", "Jacket", "Куртка", "A1"),
  w("Schoen", "Обувь", "Shoe", "Взуття", "A1"),
  w("Sok", "Носок", "Sock", "Шкарпетка", "A1"),
  w("Hoed", "Шляпа", "Hat", "Капелюх", "A1"),
  w("Sjaal", "Шарф", "Scarf", "Шарф", "A1"),
  w("Jurk", "Платье", "Dress", "Сукня", "A1"),
  w("Rok", "Юбка", "Skirt", "Спідниця", "A1"),
  w("Trui", "Свитер", "Sweater", "Светр", "A1"),
  // Weather & Nature
  w("Zon", "Солнце", "Sun", "Сонце", "A1"),
  w("Maan", "Луна", "Moon", "Місяць", "A1"),
  w("Ster", "Звезда", "Star", "Зірка", "A1"),
  w("Lucht", "Небо/воздух", "Sky/Air", "Небо/повітря", "A1"),
  w("Wolk", "Облако", "Cloud", "Хмара", "A1"),
  w("Regen", "Дождь", "Rain", "Дощ", "A1"),
  w("Sneeuw", "Снег", "Snow", "Сніг", "A1"),
  w("Wind", "Ветер", "Wind", "Вітер", "A1"),
  w("Weer", "Погода", "Weather", "Погода", "A1"),
  w("Warm", "Тёплый", "Warm", "Теплий", "A1"),
  w("Koud", "Холодный", "Cold", "Холодний", "A1"),
  w("Heet", "Жаркий", "Hot", "Гарячий", "A1"),
  w("Boom", "Дерево", "Tree", "Дерево", "A1"),
  w("Bloem", "Цветок", "Flower", "Квітка", "A1"),
  w("Gras", "Трава", "Grass", "Трава", "A1"),
  w("Berg", "Гора", "Mountain", "Гора", "A1"),
  w("Zee", "Море", "Sea", "Море", "A1"),
  w("Rivier", "Река", "River", "Річка", "A1"),
  w("Meer", "Озеро", "Lake", "Озеро", "A1"),
  w("Strand", "Пляж", "Beach", "Пляж", "A1"),
  w("Bos", "Лес", "Forest", "Ліс", "A1"),
  w("Aarde", "Земля", "Earth", "Земля", "A1"),
  // Time
  w("Dag", "День", "Day", "День", "A1"),
  w("Nacht", "Ночь", "Night", "Ніч", "A1"),
  w("Morgen", "Утро/завтра", "Morning/Tomorrow", "Ранок/завтра", "A1"),
  w("Avond", "Вечер", "Evening", "Вечір", "A1"),
  w("Week", "Неделя", "Week", "Тиждень", "A1"),
  w("Maand", "Месяц", "Month", "Місяць", "A1"),
  w("Jaar", "Год", "Year", "Рік", "A1"),
  w("Uur", "Час", "Hour", "Година", "A1"),
  w("Minuut", "Минута", "Minute", "Хвилина", "A1"),
  w("Vandaag", "Сегодня", "Today", "Сьогодні", "A1"),
  w("Gisteren", "Вчера", "Yesterday", "Вчора", "A1"),
  w("Nu", "Сейчас", "Now", "Зараз", "A1"),
  w("Later", "Позже", "Later", "Пізніше", "A1"),
  w("Altijd", "Всегда", "Always", "Завжди", "A1"),
  w("Nooit", "Никогда", "Never", "Ніколи", "A1"),
  w("Soms", "Иногда", "Sometimes", "Іноді", "A1"),
  w("Vaak", "Часто", "Often", "Часто", "A1"),
  // Days
  w("Maandag", "Понедельник", "Monday", "Понеділок", "A1"),
  w("Dinsdag", "Вторник", "Tuesday", "Вівторок", "A1"),
  w("Woensdag", "Среда", "Wednesday", "Середа", "A1"),
  w("Donderdag", "Четверг", "Thursday", "Четвер", "A1"),
  w("Vrijdag", "Пятница", "Friday", "П'ятниця", "A1"),
  w("Zaterdag", "Суббота", "Saturday", "Субота", "A1"),
  w("Zondag", "Воскресенье", "Sunday", "Неділя", "A1"),
  // Months
  w("Januari", "Январь", "January", "Січень", "A1"),
  w("Februari", "Февраль", "February", "Лютий", "A1"),
  w("Maart", "Март", "March", "Березень", "A1"),
  w("April", "Апрель", "April", "Квітень", "A1"),
  w("Mei", "Май", "May", "Травень", "A1"),
  w("Juni", "Июнь", "June", "Червень", "A1"),
  w("Juli", "Июль", "July", "Липень", "A1"),
  w("Augustus", "Август", "August", "Серпень", "A1"),
  w("September", "Сентябрь", "September", "Вересень", "A1"),
  w("Oktober", "Октябрь", "October", "Жовтень", "A1"),
  w("November", "Ноябрь", "November", "Листопад", "A1"),
  w("December", "Декабрь", "December", "Грудень", "A1"),
  // Seasons
  w("Lente", "Весна", "Spring", "Весна", "A1"),
  w("Zomer", "Лето", "Summer", "Літо", "A1"),
  w("Herfst", "Осень", "Autumn", "Осінь", "A1"),
  w("Winter", "Зима", "Winter", "Зима", "A1"),
  // Basic verbs
  w("Zijn", "Быть", "To be", "Бути", "A1"),
  w("Hebben", "Иметь", "To have", "Мати", "A1"),
  w("Gaan", "Идти", "To go", "Йти", "A1"),
  w("Komen", "Приходить", "To come", "Приходити", "A1"),
  w("Zien", "Видеть", "To see", "Бачити", "A1"),
  w("Horen", "Слышать", "To hear", "Чути", "A1"),
  w("Spreken", "Говорить", "To speak", "Говорити", "A1"),
  w("Lezen", "Читать", "To read", "Читати", "A1"),
  w("Schrijven", "Писать", "To write", "Писати", "A1"),
  w("Luisteren", "Слушать", "To listen", "Слухати", "A1"),
  w("Werken", "Работать", "To work", "Працювати", "A1"),
  w("Spelen", "Играть", "To play", "Грати", "A1"),
  w("Slapen", "Спать", "To sleep", "Спати", "A1"),
  w("Eten", "Есть", "To eat", "Їсти", "A1"),
  w("Drinken", "Пить", "To drink", "Пити", "A1"),
  w("Kopen", "Покупать", "To buy", "Купувати", "A1"),
  w("Leren", "Учить", "To learn", "Вчити", "A1"),
  w("Wonen", "Жить/проживать", "To live", "Жити/мешкати", "A1"),
  w("Rijden", "Ехать", "To drive", "Їхати", "A1"),
  w("Lopen", "Ходить/бегать", "To walk/run", "Ходити/бігати", "A1"),
  w("Zitten", "Сидеть", "To sit", "Сидіти", "A1"),
  w("Staan", "Стоять", "To stand", "Стояти", "A1"),
  w("Liggen", "Лежать", "To lie", "Лежати", "A1"),
  w("Lachen", "Смеяться", "To laugh", "Сміятися", "A1"),
  w("Huilen", "Плакать", "To cry", "Плакати", "A1"),
  w("Helpen", "Помогать", "To help", "Допомагати", "A1"),
  w("Geven", "Давать", "To give", "Давати", "A1"),
  w("Nemen", "Брать", "To take", "Брати", "A1"),
  w("Maken", "Делать", "To make", "Робити", "A1"),
  w("Doen", "Делать", "To do", "Робити", "A1"),
  w("Willen", "Хотеть", "To want", "Хотіти", "A1"),
  w("Kunnen", "Мочь", "Can", "Могти", "A1"),
  w("Moeten", "Должен", "Must", "Мусити", "A1"),
  w("Weten", "Знать", "To know", "Знати", "A1"),
  w("Denken", "Думать", "To think", "Думати", "A1"),
  w("Voelen", "Чувствовать", "To feel", "Відчувати", "A1"),
  w("Kijken", "Смотреть", "To look/watch", "Дивитися", "A1"),
  w("Zoeken", "Искать", "To search", "Шукати", "A1"),
  w("Vinden", "Находить", "To find", "Знаходити", "A1"),
  w("Wachten", "Ждать", "To wait", "Чекати", "A1"),
  w("Beginnen", "Начинать", "To begin", "Починати", "A1"),
  w("Vragen", "Спрашивать", "To ask", "Питати", "A1"),
  w("Antwoorden", "Отвечать", "To answer", "Відповідати", "A1"),
  w("Stoppen", "Останавливать", "To stop", "Зупиняти", "A1"),
  w("Vertellen", "Рассказывать", "To tell", "Розповідати", "A1"),
  w("Vallen", "Падать", "To fall", "Падати", "A1"),
  w("Groeien", "Расти", "To grow", "Рости", "A1"),
  w("Bewegen", "Двигаться", "To move", "Рухатися", "A1"),
  w("Openen", "Открывать", "To open", "Відкривати", "A1"),
  w("Sluiten", "Закрывать", "To close", "Закривати", "A1"),
  w("Dragen", "Нести/носить", "To carry/wear", "Нести/носити", "A1"),
  w("Wassen", "Мыть", "To wash", "Мити", "A1"),
  // Basic adjectives
  w("Groot", "Большой", "Big", "Великий", "A1"),
  w("Klein", "Маленький", "Small", "Маленький", "A1"),
  w("Mooi", "Красивый", "Beautiful", "Гарний", "A1"),
  w("Lelijk", "Уродливый", "Ugly", "Потворний", "A1"),
  w("Goed", "Хороший", "Good", "Добрий", "A1"),
  w("Slecht", "Плохой", "Bad", "Поганий", "A1"),
  w("Nieuw", "Новый", "New", "Новий", "A1"),
  w("Oud", "Старый", "Old", "Старий", "A1"),
  w("Jong", "Молодой", "Young", "Молодий", "A1"),
  w("Lang", "Длинный/высокий", "Long/Tall", "Довгий/високий", "A1"),
  w("Kort", "Короткий", "Short", "Короткий", "A1"),
  w("Snel", "Быстрый", "Fast", "Швидкий", "A1"),
  w("Langzaam", "Медленный", "Slow", "Повільний", "A1"),
  w("Sterk", "Сильный", "Strong", "Сильний", "A1"),
  w("Duur", "Дорогой", "Expensive", "Дорогий", "A1"),
  w("Goedkoop", "Дешёвый", "Cheap", "Дешевий", "A1"),
  w("Vol", "Полный", "Full", "Повний", "A1"),
  w("Leeg", "Пустой", "Empty", "Порожній", "A1"),
  w("Nat", "Мокрый", "Wet", "Мокрий", "A1"),
  w("Droog", "Сухой", "Dry", "Сухий", "A1"),
  w("Schoon", "Чистый", "Clean", "Чистий", "A1"),
  w("Blij", "Счастливый", "Happy", "Щасливий", "A1"),
  w("Boos", "Злой", "Angry", "Злий", "A1"),
  w("Moe", "Усталый", "Tired", "Втомлений", "A1"),
  w("Ziek", "Больной", "Sick", "Хворий", "A1"),
  w("Gezond", "Здоровый", "Healthy", "Здоровий", "A1"),
  w("Lekker", "Вкусный", "Tasty", "Смачний", "A1"),
  w("Makkelijk", "Лёгкий", "Easy", "Легкий", "A1"),
  w("Moeilijk", "Трудный", "Difficult", "Важкий", "A1"),
  w("Interessant", "Интересный", "Interesting", "Цікавий", "A1"),
  w("Belangrijk", "Важный", "Important", "Важливий", "A1"),
  w("Vriendelijk", "Дружелюбный", "Friendly", "Привітний", "A1"),
  w("Leuk", "Приятный/весёлый", "Nice/Fun", "Приємний/веселий", "A1"),
  w("Vreemd", "Странный", "Strange", "Дивний", "A1"),
  w("Donker", "Тёмный", "Dark", "Темний", "A1"),
  w("Lief", "Милый/добрый", "Sweet/Dear", "Милий/любий", "A1"),
  // Places
  w("Straat", "Улица", "Street", "Вулиця", "A1"),
  w("Park", "Парк", "Park", "Парк", "A1"),
  w("Ziekenhuis", "Больница", "Hospital", "Лікарня", "A1"),
  w("Apotheek", "Аптека", "Pharmacy", "Аптека", "A1"),
  w("Station", "Станция", "Station", "Станція", "A1"),
  w("Restaurant", "Ресторан", "Restaurant", "Ресторан", "A1"),
  w("Supermarkt", "Супермаркет", "Supermarket", "Супермаркет", "A1"),
  w("Bioscoop", "Кинотеатр", "Cinema", "Кінотеатр", "A1"),
  w("Museum", "Музей", "Museum", "Музей", "A1"),
  w("Bibliotheek", "Библиотека", "Library", "Бібліотека", "A1"),
  w("Kerk", "Церковь", "Church", "Церква", "A1"),
  w("Hotel", "Отель", "Hotel", "Готель", "A1"),
  w("Kantoor", "Офис", "Office", "Офіс", "A1"),
  // Common objects
  w("Telefoon", "Телефон", "Phone", "Телефон", "A1"),
  w("Computer", "Компьютер", "Computer", "Комп'ютер", "A1"),
  w("Boek", "Книга", "Book", "Книга", "A1"),
  w("Pen", "Ручка", "Pen", "Ручка", "A1"),
  w("Tas", "Сумка", "Bag", "Сумка", "A1"),
  w("Sleutel", "Ключ", "Key", "Ключ", "A1"),
  w("Geld", "Деньги", "Money", "Гроші", "A1"),
  w("Bril", "Очки", "Glasses", "Окуляри", "A1"),
  w("Paraplu", "Зонт", "Umbrella", "Парасоля", "A1"),
  w("Fiets", "Велосипед", "Bicycle", "Велосипед", "A1"),
  w("Auto", "Машина", "Car", "Машина", "A1"),
  w("Bus", "Автобус", "Bus", "Автобус", "A1"),
  w("Trein", "Поезд", "Train", "Потяг", "A1"),
  w("Vliegtuig", "Самолёт", "Airplane", "Літак", "A1"),
  w("Boot", "Лодка", "Boat", "Човен", "A1"),
  w("Foto", "Фотография", "Photo", "Фотографія", "A1"),
  w("Cadeau", "Подарок", "Gift", "Подарунок", "A1"),
  w("Mes", "Нож", "Knife", "Ніж", "A1"),
  w("Vork", "Вилка", "Fork", "Виделка", "A1"),
  w("Lepel", "Ложка", "Spoon", "Ложка", "A1"),
  w("Bord", "Тарелка", "Plate", "Тарілка", "A1"),
  w("Glas", "Стакан", "Glass", "Склянка", "A1"),
  w("Kopje", "Чашка", "Cup", "Чашка", "A1"),
  w("Fles", "Бутылка", "Bottle", "Пляшка", "A1"),
  // Prepositions & question words
  w("In", "В", "In", "В", "A1"),
  w("Op", "На", "On", "На", "A1"),
  w("Onder", "Под", "Under", "Під", "A1"),
  w("Naast", "Рядом", "Next to", "Поруч", "A1"),
  w("Voor", "Перед/для", "In front of/For", "Перед/для", "A1"),
  w("Achter", "За/позади", "Behind", "За/позаду", "A1"),
  w("Tussen", "Между", "Between", "Між", "A1"),
  w("Met", "С", "With", "З", "A1"),
  w("Zonder", "Без", "Without", "Без", "A1"),
  w("Naar", "К/в (направление)", "To/Towards", "До/в (напрямок)", "A1"),
  w("Van", "От/из", "From/Of", "Від/з", "A1"),
  w("Hier", "Здесь", "Here", "Тут", "A1"),
  w("Daar", "Там", "There", "Там", "A1"),
  w("Waar", "Где", "Where", "Де", "A1"),
  w("Wie", "Кто", "Who", "Хто", "A1"),
  w("Wat", "Что", "What", "Що", "A1"),
  w("Wanneer", "Когда", "When", "Коли", "A1"),
  w("Waarom", "Почему", "Why", "Чому", "A1"),
  w("Hoe", "Как", "How", "Як", "A1"),
  w("Hoeveel", "Сколько", "How much/many", "Скільки", "A1"),
  w("Dit", "Это", "This", "Це", "A1"),
  w("Dat", "То", "That", "То", "A1"),
  w("Veel", "Много", "Much/Many", "Багато", "A1"),
  w("Weinig", "Мало", "Few/Little", "Мало", "A1"),
  w("Meer", "Больше", "More", "Більше", "A1"),
  w("Minder", "Меньше", "Less", "Менше", "A1"),
  w("Genoeg", "Достаточно", "Enough", "Достатньо", "A1"),
  w("Samen", "Вместе", "Together", "Разом", "A1"),
  w("Alleen", "Один/только", "Alone/Only", "Один/тільки", "A1"),
  w("Ook", "Тоже", "Also", "Також", "A1"),
  w("Al", "Уже", "Already", "Вже", "A1"),
  w("Heel", "Очень", "Very", "Дуже", "A1"),
  w("Misschien", "Может быть", "Maybe", "Можливо", "A1"),
  w("Precies", "Точно", "Exactly", "Точно", "A1"),
  w("Bijna", "Почти", "Almost", "Майже", "A1"),
  // Pronouns & basics
  w("Ik", "Я", "I", "Я", "A1"),
  w("Jij", "Ты", "You", "Ти", "A1"),
  w("Hij", "Он", "He", "Він", "A1"),
  w("Zij", "Она/Они", "She/They", "Вона/Вони", "A1"),
  w("Wij", "Мы", "We", "Ми", "A1"),
  w("Mijn", "Мой", "My", "Мій", "A1"),
  w("Jouw", "Твой", "Your", "Твій", "A1"),
  // School
  w("Leraar", "Учитель", "Teacher", "Вчитель", "A1"),
  w("Leerling", "Ученик", "Student", "Учень", "A1"),
  w("Les", "Урок", "Lesson", "Урок", "A1"),
  w("Huiswerk", "Домашняя работа", "Homework", "Домашнє завдання", "A1"),
  w("Vraag", "Вопрос", "Question", "Питання", "A1"),
  w("Antwoord", "Ответ", "Answer", "Відповідь", "A1"),
  w("Potlood", "Карандаш", "Pencil", "Олівець", "A1"),
  w("Papier", "Бумага", "Paper", "Папір", "A1"),
  // Countries
  w("Nederland", "Нидерланды", "Netherlands", "Нідерланди", "A1"),
  w("België", "Бельгия", "Belgium", "Бельгія", "A1"),
  w("Duitsland", "Германия", "Germany", "Німеччина", "A1"),
  w("Frankrijk", "Франция", "France", "Франція", "A1"),
  w("Engeland", "Англия", "England", "Англія", "A1"),
  w("Spanje", "Испания", "Spain", "Іспанія", "A1"),
  w("Italië", "Италия", "Italy", "Італія", "A1"),
  w("Amerika", "Америка", "America", "Америка", "A1"),
  w("Oekraïne", "Украина", "Ukraine", "Україна", "A1"),
  // Materials
  w("Hout", "Дерево (материал)", "Wood", "Дерево (матеріал)", "A1"),
  w("Metaal", "Металл", "Metal", "Метал", "A1"),
  w("Plastic", "Пластик", "Plastic", "Пластик", "A1"),
  w("Goud", "Золото", "Gold", "Золото", "A1"),
  w("Zilver", "Серебро", "Silver", "Срібло", "A1"),
  // Languages
  w("Nederlands", "Нидерландский", "Dutch", "Нідерландська", "A1"),
  w("Engels", "Английский", "English", "Англійська", "A1"),
  w("Duits", "Немецкий", "German", "Німецька", "A1"),
  w("Frans", "Французский", "French", "Французька", "A1"),
  w("Taal", "Язык", "Language", "Мова", "A1"),
  // Misc A1
  w("Naam", "Имя", "Name", "Ім'я", "A1"),
  w("Adres", "Адрес", "Address", "Адреса", "A1"),
  w("Nummer", "Номер", "Number", "Номер", "A1"),
  w("Probleem", "Проблема", "Problem", "Проблема", "A1"),
  w("Film", "Фильм", "Film", "Фільм", "A1"),
  w("Muziek", "Музыка", "Music", "Музика", "A1"),
  w("Sport", "Спорт", "Sport", "Спорт", "A1"),
  w("Voetbal", "Футбол", "Football", "Футбол", "A1"),
  w("Verjaardag", "День рождения", "Birthday", "День народження", "A1"),
  w("Reis", "Поездка", "Trip", "Подорож", "A1"),
  w("Vakantie", "Отпуск/каникулы", "Holiday", "Відпустка/канікули", "A1"),
  w("Dokter", "Врач", "Doctor", "Лікар", "A1"),
  w("Politie", "Полиция", "Police", "Поліція", "A1"),
  w("Prijs", "Цена", "Price", "Ціна", "A1"),
  w("Paspoort", "Паспорт", "Passport", "Паспорт", "A1"),
  w("Weg", "Дорога", "Road", "Дорога", "A1"),
  w("Hoek", "Угол", "Corner", "Кут", "A1"),
  w("Einde", "Конец", "End", "Кінець", "A1"),
  w("Begin", "Начало", "Beginning", "Початок", "A1"),
  w("Voorbeeld", "Пример", "Example", "Приклад", "A1"),
  w("Verschil", "Разница", "Difference", "Різниця", "A1"),
  w("Succes", "Успех", "Success", "Успіх", "A1"),
  w("Geluk", "Удача/счастье", "Luck/Happiness", "Удача/щастя", "A1"),
  w("Rust", "Покой", "Rest/Peace", "Спокій", "A1"),
  w("Hoop", "Надежда", "Hope", "Надія", "A1"),
  w("Pijn", "Боль", "Pain", "Біль", "A1"),
  w("Honger", "Голод", "Hunger", "Голод", "A1"),
  w("Dorst", "Жажда", "Thirst", "Спрага", "A1"),

  // ===== A2 - ELEMENTARY =====
  // Transport & Travel
  w("Vertrekken", "Отправляться", "To depart", "Від'їжджати", "A2"),
  w("Aankomen", "Прибывать", "To arrive", "Прибувати", "A2"),
  w("Overstappen", "Пересаживаться", "To transfer", "Пересідати", "A2"),
  w("Perron", "Платформа", "Platform", "Платформа", "A2"),
  w("Halte", "Остановка", "Stop", "Зупинка", "A2"),
  w("Retour", "Туда-обратно", "Return", "Туди-назад", "A2"),
  w("Vertraging", "Задержка", "Delay", "Затримка", "A2"),
  w("Richting", "Направление", "Direction", "Напрямок", "A2"),
  w("Benzine", "Бензин", "Gasoline", "Бензин", "A2"),
  w("Verkeer", "Движение", "Traffic", "Рух", "A2"),
  w("Stoplicht", "Светофор", "Traffic light", "Світлофор", "A2"),
  w("Kruispunt", "Перекрёсток", "Intersection", "Перехрестя", "A2"),
  w("Snelweg", "Автострада", "Highway", "Автострада", "A2"),
  w("Brug", "Мост", "Bridge", "Міст", "A2"),
  w("Tram", "Трамвай", "Tram", "Трамвай", "A2"),
  w("Metro", "Метро", "Metro", "Метро", "A2"),
  w("Taxi", "Такси", "Taxi", "Таксі", "A2"),
  // Shopping
  w("Winkel", "Магазин", "Shop", "Магазин", "A2"),
  w("Winkelen", "Ходить за покупками", "To shop", "Ходити за покупками", "A2"),
  w("Klant", "Клиент", "Customer", "Клієнт", "A2"),
  w("Kassa", "Касса", "Cash register", "Каса", "A2"),
  w("Boodschappen", "Продукты", "Groceries", "Продукти", "A2"),
  w("Maat", "Размер", "Size", "Розмір", "A2"),
  w("Passen", "Примерять", "To fit/try on", "Приміряти", "A2"),
  w("Contant", "Наличные", "Cash", "Готівка", "A2"),
  w("Pinnen", "Платить картой", "To pay by card", "Платити карткою", "A2"),
  w("Aanbieding", "Предложение/акция", "Offer/Sale", "Пропозиція/акція", "A2"),
  w("Gratis", "Бесплатно", "Free", "Безкоштовно", "A2"),
  w("Korting", "Скидка", "Discount", "Знижка", "A2"),
  w("Bakker", "Пекарня", "Bakery", "Пекарня", "A2"),
  // Health
  w("Hoofdpijn", "Головная боль", "Headache", "Головний біль", "A2"),
  w("Buikpijn", "Боль в животе", "Stomach ache", "Біль у животі", "A2"),
  w("Koorts", "Температура", "Fever", "Температура", "A2"),
  w("Verkoudheid", "Простуда", "Cold", "Застуда", "A2"),
  w("Hoesten", "Кашлять", "To cough", "Кашляти", "A2"),
  w("Medicijn", "Лекарство", "Medicine", "Ліки", "A2"),
  w("Afspraak", "Встреча/приём", "Appointment", "Зустріч/прийом", "A2"),
  w("Tandarts", "Стоматолог", "Dentist", "Стоматолог", "A2"),
  w("Allergie", "Аллергия", "Allergy", "Алергія", "A2"),
  w("Oefening", "Упражнение", "Exercise", "Вправа", "A2"),
  // Work & Professions
  w("Baan", "Работа/должность", "Job", "Робота/посада", "A2"),
  w("Salaris", "Зарплата", "Salary", "Зарплата", "A2"),
  w("Baas", "Начальник", "Boss", "Начальник", "A2"),
  w("Collega", "Коллега", "Colleague", "Колега", "A2"),
  w("Vergadering", "Собрание", "Meeting", "Нарада", "A2"),
  w("Ervaring", "Опыт", "Experience", "Досвід", "A2"),
  w("Kok", "Повар", "Cook", "Кухар", "A2"),
  w("Ingenieur", "Инженер", "Engineer", "Інженер", "A2"),
  w("Advocaat", "Адвокат", "Lawyer", "Адвокат", "A2"),
  w("Journalist", "Журналист", "Journalist", "Журналіст", "A2"),
  w("Kunstenaar", "Художник", "Artist", "Художник", "A2"),
  w("Schrijver", "Писатель", "Writer", "Письменник", "A2"),
  w("Boer", "Фермер", "Farmer", "Фермер", "A2"),
  w("Kapper", "Парикмахер", "Hairdresser", "Перукар", "A2"),
  w("Piloot", "Пилот", "Pilot", "Пілот", "A2"),
  // Emotions
  w("Gelukkig", "Счастливый", "Happy", "Щасливий", "A2"),
  w("Verdrietig", "Грустный", "Sad", "Сумний", "A2"),
  w("Zenuwachtig", "Нервный", "Nervous", "Нервовий", "A2"),
  w("Trots", "Гордый", "Proud", "Гордий", "A2"),
  w("Verlegen", "Застенчивый", "Shy", "Сором'язливий", "A2"),
  w("Teleurgesteld", "Разочарованный", "Disappointed", "Розчарований", "A2"),
  w("Verbaasd", "Удивлённый", "Surprised", "Здивований", "A2"),
  w("Tevreden", "Довольный", "Satisfied", "Задоволений", "A2"),
  w("Eenzaam", "Одинокий", "Lonely", "Самотній", "A2"),
  w("Rustig", "Спокойный", "Calm", "Спокійний", "A2"),
  w("Eerlijk", "Честный", "Honest", "Чесний", "A2"),
  w("Grappig", "Смешной", "Funny", "Смішний", "A2"),
  w("Slim", "Умный", "Smart", "Розумний", "A2"),
  w("Lui", "Ленивый", "Lazy", "Лінивий", "A2"),
  w("Geduldig", "Терпеливый", "Patient", "Терплячий", "A2"),
  w("Nieuwsgierig", "Любопытный", "Curious", "Цікавий", "A2"),
  w("Dapper", "Храбрый", "Brave", "Хоробрий", "A2"),
  // Kitchen & Cooking
  w("Koken", "Готовить", "To cook", "Готувати", "A2"),
  w("Bakken", "Печь/жарить", "To bake/fry", "Пекти/смажити", "A2"),
  w("Snijden", "Резать", "To cut", "Різати", "A2"),
  w("Roeren", "Мешать", "To stir", "Мішати", "A2"),
  w("Koelkast", "Холодильник", "Refrigerator", "Холодильник", "A2"),
  w("Oven", "Духовка", "Oven", "Духовка", "A2"),
  w("Pan", "Сковорода", "Pan", "Сковорідка", "A2"),
  w("Pot", "Кастрюля", "Pot", "Каструля", "A2"),
  w("Afwassen", "Мыть посуду", "To do dishes", "Мити посуд", "A2"),
  w("Recept", "Рецепт", "Recipe", "Рецепт", "A2"),
  w("Gerecht", "Блюдо", "Dish", "Страва", "A2"),
  // House & Cleaning
  w("Schoonmaken", "Убирать", "To clean", "Прибирати", "A2"),
  w("Stofzuigen", "Пылесосить", "To vacuum", "Пилососити", "A2"),
  w("Strijken", "Гладить", "To iron", "Прасувати", "A2"),
  w("Opruimen", "Наводить порядок", "To tidy up", "Прибирати", "A2"),
  w("Verhuizen", "Переезжать", "To move", "Переїжджати", "A2"),
  w("Huur", "Аренда", "Rent", "Оренда", "A2"),
  w("Buurman", "Сосед", "Neighbour", "Сусід", "A2"),
  w("Lift", "Лифт", "Elevator", "Ліфт", "A2"),
  w("Ingang", "Вход", "Entrance", "Вхід", "A2"),
  w("Uitgang", "Выход", "Exit", "Вихід", "A2"),
  w("Handdoek", "Полотенце", "Towel", "Рушник", "A2"),
  w("Zeep", "Мыло", "Soap", "Мило", "A2"),
  w("Spiegel", "Зеркало", "Mirror", "Дзеркало", "A2"),
  w("Douche", "Душ", "Shower", "Душ", "A2"),
  w("Wasmachine", "Стиральная машина", "Washing machine", "Пральна машина", "A2"),
  // Nature
  w("Natuur", "Природа", "Nature", "Природа", "A2"),
  w("Milieu", "Окружающая среда", "Environment", "Довкілля", "A2"),
  w("Dier", "Животное", "Animal", "Тварина", "A2"),
  w("Plant", "Растение", "Plant", "Рослина", "A2"),
  w("Blad", "Лист", "Leaf", "Листок", "A2"),
  w("Steen", "Камень", "Stone", "Камінь", "A2"),
  w("Zand", "Песок", "Sand", "Пісок", "A2"),
  w("Ijs", "Лёд", "Ice", "Лід", "A2"),
  w("Storm", "Шторм", "Storm", "Шторм", "A2"),
  w("Mist", "Туман", "Fog", "Туман", "A2"),
  w("Regenboog", "Радуга", "Rainbow", "Веселка", "A2"),
  // Daily activities
  w("Opstaan", "Вставать", "To get up", "Вставати", "A2"),
  w("Aankleden", "Одеваться", "To get dressed", "Одягатися", "A2"),
  w("Douchen", "Принимать душ", "To shower", "Приймати душ", "A2"),
  w("Ontbijten", "Завтракать", "To have breakfast", "Снідати", "A2"),
  w("Lunchen", "Обедать", "To have lunch", "Обідати", "A2"),
  w("Wandelen", "Гулять", "To walk", "Гуляти", "A2"),
  w("Fietsen", "Кататься на велосипеде", "To cycle", "Їздити на велосипеді", "A2"),
  w("Bellen", "Звонить", "To call", "Дзвонити", "A2"),
  w("Uitnodigen", "Приглашать", "To invite", "Запрошувати", "A2"),
  w("Bezoeken", "Навещать", "To visit", "Відвідувати", "A2"),
  // Hobbies
  w("Hobby", "Хобби", "Hobby", "Хобі", "A2"),
  w("Tekenen", "Рисовать", "To draw", "Малювати", "A2"),
  w("Fotograferen", "Фотографировать", "To photograph", "Фотографувати", "A2"),
  w("Hardlopen", "Бегать", "To jog", "Бігати", "A2"),
  w("Zwemmen", "Плавать", "To swim", "Плавати", "A2"),
  w("Dansen", "Танцевать", "To dance", "Танцювати", "A2"),
  w("Zingen", "Петь", "To sing", "Співати", "A2"),
  w("Gitaar", "Гитара", "Guitar", "Гітара", "A2"),
  w("Piano", "Пианино", "Piano", "Піаніно", "A2"),
  w("Concert", "Концерт", "Concert", "Концерт", "A2"),
  w("Theater", "Театр", "Theater", "Театр", "A2"),
  w("Wedstrijd", "Соревнование", "Competition/Match", "Змагання/матч", "A2"),
  // Communication
  w("Gesprek", "Разговор", "Conversation", "Розмова", "A2"),
  w("Betekenis", "Значение", "Meaning", "Значення", "A2"),
  w("Woord", "Слово", "Word", "Слово", "A2"),
  w("Zin", "Предложение", "Sentence", "Речення", "A2"),
  w("Brief", "Письмо", "Letter", "Лист", "A2"),
  w("Bericht", "Сообщение", "Message", "Повідомлення", "A2"),
  w("Informatie", "Информация", "Information", "Інформація", "A2"),
  w("Uitleggen", "Объяснять", "To explain", "Пояснювати", "A2"),
  w("Vertalen", "Переводить", "To translate", "Перекладати", "A2"),
  w("Herhalen", "Повторять", "To repeat", "Повторювати", "A2"),
  w("Woordenboek", "Словарь", "Dictionary", "Словник", "A2"),
  w("Cursus", "Курс", "Course", "Курс", "A2"),
  // Technology
  w("Internet", "Интернет", "Internet", "Інтернет", "A2"),
  w("Website", "Веб-сайт", "Website", "Веб-сайт", "A2"),
  w("Wachtwoord", "Пароль", "Password", "Пароль", "A2"),
  w("Scherm", "Экран", "Screen", "Екран", "A2"),
  w("Toetsenbord", "Клавиатура", "Keyboard", "Клавіатура", "A2"),
  w("Printer", "Принтер", "Printer", "Принтер", "A2"),
  w("Oplader", "Зарядка", "Charger", "Зарядка", "A2"),
  w("Televisie", "Телевизор", "Television", "Телевізор", "A2"),
  // Education
  w("Opleiding", "Образование", "Education", "Освіта", "A2"),
  w("Universiteit", "Университет", "University", "Університет", "A2"),
  w("Student", "Студент", "Student", "Студент", "A2"),
  w("Diploma", "Диплом", "Diploma", "Диплом", "A2"),
  w("Cijfer", "Оценка", "Grade", "Оцінка", "A2"),
  w("Toets", "Тест", "Test", "Тест", "A2"),
  w("Kennis", "Знания", "Knowledge", "Знання", "A2"),
  // Everyday adjectives
  w("Gezellig", "Уютный/приятный", "Cozy/Pleasant", "Затишний/приємний", "A2"),
  w("Geweldig", "Потрясающий", "Wonderful", "Чудовий", "A2"),
  w("Speciaal", "Особенный", "Special", "Особливий", "A2"),
  w("Populair", "Популярный", "Popular", "Популярний", "A2"),
  w("Modern", "Современный", "Modern", "Сучасний", "A2"),
  w("Mogelijk", "Возможный", "Possible", "Можливий", "A2"),
  w("Nodig", "Необходимый", "Necessary", "Необхідний", "A2"),
  w("Beschikbaar", "Доступный", "Available", "Доступний", "A2"),
  w("Druk", "Занятый", "Busy", "Зайнятий", "A2"),
  w("Vrij", "Свободный", "Free", "Вільний", "A2"),
  w("Vers", "Свежий", "Fresh", "Свіжий", "A2"),
  // Relationships
  w("Vriend", "Друг", "Friend", "Друг", "A2"),
  w("Trouwen", "Жениться", "To marry", "Одружуватися", "A2"),
  w("Bruiloft", "Свадьба", "Wedding", "Весілля", "A2"),
  w("Relatie", "Отношения", "Relationship", "Стосунки", "A2"),
  w("Verliefd", "Влюблённый", "In love", "Закоханий", "A2"),
  w("Herinneren", "Вспоминать", "To remember", "Згадувати", "A2"),
  w("Vergeten", "Забывать", "To forget", "Забувати", "A2"),
  w("Liefde", "Любовь", "Love", "Кохання", "A2"),
  w("Vriendschap", "Дружба", "Friendship", "Дружба", "A2"),
  w("Vertrouwen", "Доверие", "Trust", "Довіра", "A2"),
  w("Respect", "Уважение", "Respect", "Повага", "A2"),
  w("Advies", "Совет", "Advice", "Порада", "A2"),
  w("Mening", "Мнение", "Opinion", "Думка", "A2"),
  w("Grap", "Шутка", "Joke", "Жарт", "A2"),
  w("Verrassing", "Сюрприз", "Surprise", "Сюрприз", "A2"),
  // Holidays
  w("Kerstmis", "Рождество", "Christmas", "Різдво", "A2"),
  w("Pasen", "Пасха", "Easter", "Великдень", "A2"),
  w("Sinterklaas", "Синтерклаас", "Sinterklaas", "Синтерклаас", "A2"),
  w("Koningsdag", "День короля", "King's Day", "День короля", "A2"),
  w("Vuurwerk", "Фейерверк", "Fireworks", "Феєрверк", "A2"),
  // Sports
  w("Basketbal", "Баскетбол", "Basketball", "Баскетбол", "A2"),
  w("Volleybal", "Волейбол", "Volleyball", "Волейбол", "A2"),
  w("Fitness", "Фитнес", "Fitness", "Фітнес", "A2"),
  w("Trainer", "Тренер", "Coach", "Тренер", "A2"),
  w("Team", "Команда", "Team", "Команда", "A2"),
  // More A2 verbs
  w("Huren", "Арендовать", "To rent", "Орендувати", "A2"),
  w("Reserveren", "Бронировать", "To reserve", "Бронювати", "A2"),
  w("Bestellen", "Заказывать", "To order", "Замовляти", "A2"),
  w("Verzenden", "Отправлять", "To send", "Відправляти", "A2"),
  w("Ontvangen", "Получать", "To receive", "Отримувати", "A2"),
  w("Bezorgen", "Доставлять", "To deliver", "Доставляти", "A2"),
  w("Sparen", "Копить", "To save", "Заощаджувати", "A2"),
  w("Uitgeven", "Тратить", "To spend", "Витрачати", "A2"),
  w("Betalen", "Платить", "To pay", "Платити", "A2"),
  w("Feliciteren", "Поздравлять", "To congratulate", "Вітати", "A2"),
  w("Ontmoeten", "Встречать", "To meet", "Зустрічати", "A2"),
  w("Voorstellen", "Представлять", "To introduce", "Представляти", "A2"),
  // Dutch culture
  w("Molen", "Мельница", "Windmill", "Млин", "A2"),
  w("Tulp", "Тюльпан", "Tulip", "Тюльпан", "A2"),
  w("Gracht", "Канал", "Canal", "Канал", "A2"),
  w("Dijk", "Дамба", "Dike", "Дамба", "A2"),
  w("Huisarts", "Семейный врач", "General practitioner", "Сімейний лікар", "A2"),
  // Money
  w("Bankpas", "Банковская карта", "Debit card", "Банківська картка", "A2"),
  w("Geldautomaat", "Банкомат", "ATM", "Банкомат", "A2"),
  w("Wisselgeld", "Сдача", "Change", "Решта", "A2"),
  w("Fooi", "Чаевые", "Tip", "Чайові", "A2"),
  w("Rekening", "Счёт", "Bill/Account", "Рахунок", "A2"),
  // Clothes A2
  w("Spijkerbroek", "Джинсы", "Jeans", "Джинси", "A2"),
  w("Sportschoenen", "Кроссовки", "Sneakers", "Кросівки", "A2"),
  w("Laarzen", "Сапоги", "Boots", "Чоботи", "A2"),
  w("Pak", "Костюм", "Suit", "Костюм", "A2"),
  w("Stropdas", "Галстук", "Tie", "Краватка", "A2"),
  w("Zonnebril", "Солнечные очки", "Sunglasses", "Сонцезахисні окуляри", "A2"),
  w("Rugzak", "Рюкзак", "Backpack", "Рюкзак", "A2"),

  // ===== B1 - INTERMEDIATE =====
  // Abstract concepts
  w("Begrip", "Понятие", "Concept", "Поняття", "B1"),
  w("Gevolg", "Последствие", "Consequence", "Наслідок", "B1"),
  w("Oorzaak", "Причина", "Cause", "Причина", "B1"),
  w("Doel", "Цель", "Goal", "Ціль", "B1"),
  w("Resultaat", "Результат", "Result", "Результат", "B1"),
  w("Proces", "Процесс", "Process", "Процес", "B1"),
  w("Methode", "Метод", "Method", "Метод", "B1"),
  w("Systeem", "Система", "System", "Система", "B1"),
  w("Structuur", "Структура", "Structure", "Структура", "B1"),
  w("Kwaliteit", "Качество", "Quality", "Якість", "B1"),
  w("Principe", "Принцип", "Principle", "Принцип", "B1"),
  w("Theorie", "Теория", "Theory", "Теорія", "B1"),
  w("Praktijk", "Практика", "Practice", "Практика", "B1"),
  w("Analyse", "Анализ", "Analysis", "Аналіз", "B1"),
  // Society & Politics
  w("Overheid", "Правительство", "Government", "Уряд", "B1"),
  w("Gemeente", "Муниципалитет", "Municipality", "Муніципалітет", "B1"),
  w("Verkiezing", "Выборы", "Election", "Вибори", "B1"),
  w("Stemmen", "Голосовать", "To vote", "Голосувати", "B1"),
  w("Politiek", "Политика", "Politics", "Політика", "B1"),
  w("Democratie", "Демократия", "Democracy", "Демократія", "B1"),
  w("Wet", "Закон", "Law", "Закон", "B1"),
  w("Recht", "Право", "Right", "Право", "B1"),
  w("Plicht", "Обязанность", "Duty", "Обов'язок", "B1"),
  w("Vrijheid", "Свобода", "Freedom", "Свобода", "B1"),
  w("Gelijkheid", "Равенство", "Equality", "Рівність", "B1"),
  w("Burger", "Гражданин", "Citizen", "Громадянин", "B1"),
  w("Belasting", "Налог", "Tax", "Податок", "B1"),
  w("Verzekering", "Страхование", "Insurance", "Страхування", "B1"),
  w("Integratie", "Интеграция", "Integration", "Інтеграція", "B1"),
  // Economy
  w("Economie", "Экономика", "Economy", "Економіка", "B1"),
  w("Bedrijf", "Предприятие", "Company", "Підприємство", "B1"),
  w("Ondernemer", "Предприниматель", "Entrepreneur", "Підприємець", "B1"),
  w("Winst", "Прибыль", "Profit", "Прибуток", "B1"),
  w("Verlies", "Убыток", "Loss", "Збиток", "B1"),
  w("Investering", "Инвестиция", "Investment", "Інвестиція", "B1"),
  w("Handel", "Торговля", "Trade", "Торгівля", "B1"),
  w("Concurrentie", "Конкуренция", "Competition", "Конкуренція", "B1"),
  w("Markt", "Рынок", "Market", "Ринок", "B1"),
  w("Schuld", "Долг", "Debt", "Борг", "B1"),
  w("Lening", "Кредит", "Loan", "Позика", "B1"),
  w("Budget", "Бюджет", "Budget", "Бюджет", "B1"),
  w("Inkomen", "Доход", "Income", "Дохід", "B1"),
  w("Contract", "Контракт", "Contract", "Контракт", "B1"),
  // Media
  w("Artikel", "Статья", "Article", "Стаття", "B1"),
  w("Interview", "Интервью", "Interview", "Інтерв'ю", "B1"),
  w("Reclame", "Реклама", "Advertisement", "Реклама", "B1"),
  w("Documentaire", "Документальный фильм", "Documentary", "Документальний фільм", "B1"),
  w("Abonnement", "Подписка", "Subscription", "Підписка", "B1"),
  // Science
  w("Wetenschap", "Наука", "Science", "Наука", "B1"),
  w("Onderzoek", "Исследование", "Research", "Дослідження", "B1"),
  w("Experiment", "Эксперимент", "Experiment", "Експеримент", "B1"),
  w("Bewijs", "Доказательство", "Evidence/Proof", "Доказ", "B1"),
  w("Conclusie", "Вывод", "Conclusion", "Висновок", "B1"),
  w("Discussie", "Дискуссия", "Discussion", "Дискусія", "B1"),
  w("Argument", "Аргумент", "Argument", "Аргумент", "B1"),
  w("Samenvatting", "Резюме", "Summary", "Стислий виклад", "B1"),
  // B1 Verbs
  w("Begrijpen", "Понимать", "To understand", "Розуміти", "B1"),
  w("Proberen", "Пробовать", "To try", "Пробувати", "B1"),
  w("Beslissen", "Решать", "To decide", "Вирішувати", "B1"),
  w("Ontwikkelen", "Развивать", "To develop", "Розвивати", "B1"),
  w("Organiseren", "Организовывать", "To organize", "Організовувати", "B1"),
  w("Deelnemen", "Участвовать", "To participate", "Брати участь", "B1"),
  w("Samenwerken", "Сотрудничать", "To cooperate", "Співпрацювати", "B1"),
  w("Communiceren", "Общаться", "To communicate", "Спілкуватися", "B1"),
  w("Evalueren", "Оценивать", "To evaluate", "Оцінювати", "B1"),
  w("Plannen", "Планировать", "To plan", "Планувати", "B1"),
  w("Vergelijken", "Сравнивать", "To compare", "Порівнювати", "B1"),
  w("Produceren", "Производить", "To produce", "Виробляти", "B1"),
  w("Bestellen", "Заказывать", "To order", "Замовляти", "B1"),
  // Legal
  w("Formulier", "Бланк/форма", "Form", "Бланк/форма", "B1"),
  w("Aanvragen", "Подавать заявку", "To apply for", "Подавати заявку", "B1"),
  w("Inschrijven", "Регистрироваться", "To register", "Реєструватися", "B1"),
  w("Vergunning", "Разрешение/лицензия", "Permit/License", "Дозвіл/ліцензія", "B1"),
  w("Document", "Документ", "Document", "Документ", "B1"),
  w("Handtekening", "Подпись", "Signature", "Підпис", "B1"),
  w("Geldig", "Действительный", "Valid", "Дійсний", "B1"),
  w("Voorwaarde", "Условие", "Condition", "Умова", "B1"),
  w("Regel", "Правило", "Rule", "Правило", "B1"),
  w("Uitzondering", "Исключение", "Exception", "Виняток", "B1"),
  w("Procedure", "Процедура", "Procedure", "Процедура", "B1"),
  w("Boete", "Штраф", "Fine", "Штраф", "B1"),
  // Environment
  w("Klimaat", "Климат", "Climate", "Клімат", "B1"),
  w("Vervuiling", "Загрязнение", "Pollution", "Забруднення", "B1"),
  w("Afval", "Мусор", "Waste", "Відходи", "B1"),
  w("Recyclen", "Перерабатывать", "To recycle", "Переробляти", "B1"),
  w("Energie", "Энергия", "Energy", "Енергія", "B1"),
  w("Zonne-energie", "Солнечная энергия", "Solar energy", "Сонячна енергія", "B1"),
  w("Uitstoot", "Выброс", "Emission", "Викид", "B1"),
  w("Beschermen", "Защищать", "To protect", "Захищати", "B1"),
  w("Hernieuwbaar", "Возобновляемый", "Renewable", "Відновлюваний", "B1"),
  // Health advanced
  w("Symptoom", "Симптом", "Symptom", "Симптом", "B1"),
  w("Diagnose", "Диагноз", "Diagnosis", "Діагноз", "B1"),
  w("Behandeling", "Лечение", "Treatment", "Лікування", "B1"),
  w("Therapie", "Терапия", "Therapy", "Терапія", "B1"),
  w("Preventie", "Профилактика", "Prevention", "Профілактика", "B1"),
  w("Vaccinatie", "Вакцинация", "Vaccination", "Вакцинація", "B1"),
  w("Stress", "Стресс", "Stress", "Стрес", "B1"),
  w("Depressie", "Депрессия", "Depression", "Депресія", "B1"),
  w("Specialist", "Специалист", "Specialist", "Спеціаліст", "B1"),
  // Urban
  w("Wijk", "Район", "Neighbourhood", "Район", "B1"),
  w("Centrum", "Центр", "Centre", "Центр", "B1"),
  w("Platteland", "Сельская местность", "Countryside", "Сільська місцевість", "B1"),
  w("Inwoner", "Житель", "Inhabitant", "Мешканець", "B1"),
  w("Bevolking", "Население", "Population", "Населення", "B1"),
  w("Openbaar vervoer", "Общественный транспорт", "Public transport", "Громадський транспорт", "B1"),
  w("Fietspad", "Велосипедная дорожка", "Bike path", "Велосипедна доріжка", "B1"),
  // More B1 verbs
  w("Aanpassen", "Приспосабливать", "To adapt", "Пристосовувати", "B1"),
  w("Toepassen", "Применять", "To apply", "Застосовувати", "B1"),
  w("Uitvoeren", "Выполнять", "To carry out", "Виконувати", "B1"),
  w("Bereiken", "Достигать", "To achieve/reach", "Досягати", "B1"),
  w("Verbeteren", "Улучшать", "To improve", "Покращувати", "B1"),
  w("Voorkomen", "Предотвращать", "To prevent", "Запобігати", "B1"),
  w("Oplossen", "Решать (проблему)", "To solve", "Вирішувати (проблему)", "B1"),
  w("Ondersteunen", "Поддерживать", "To support", "Підтримувати", "B1"),
  w("Waarschuwen", "Предупреждать", "To warn", "Попереджати", "B1"),
  w("Controleren", "Контролировать", "To check/control", "Контролювати", "B1"),
  w("Ontdekken", "Открывать", "To discover", "Відкривати", "B1"),
  w("Accepteren", "Принимать", "To accept", "Приймати", "B1"),
  w("Weigeren", "Отказывать", "To refuse", "Відмовляти", "B1"),
  w("Onderhandelen", "Вести переговоры", "To negotiate", "Вести переговори", "B1"),
  // B1 adjectives
  w("Effectief", "Эффективный", "Effective", "Ефективний", "B1"),
  w("Flexibel", "Гибкий", "Flexible", "Гнучкий", "B1"),
  w("Creatief", "Творческий", "Creative", "Творчий", "B1"),
  w("Professioneel", "Профессиональный", "Professional", "Професійний", "B1"),
  w("Betrouwbaar", "Надёжный", "Reliable", "Надійний", "B1"),
  w("Verantwoordelijk", "Ответственный", "Responsible", "Відповідальний", "B1"),
  w("Onafhankelijk", "Независимый", "Independent", "Незалежний", "B1"),
  w("Internationaal", "Международный", "International", "Міжнародний", "B1"),
  w("Sociaal", "Социальный", "Social", "Соціальний", "B1"),
  w("Cultureel", "Культурный", "Cultural", "Культурний", "B1"),
  w("Wetenschappelijk", "Научный", "Scientific", "Науковий", "B1"),
  w("Financieel", "Финансовый", "Financial", "Фінансовий", "B1"),
  w("Duurzaam", "Устойчивый/прочный", "Sustainable/Durable", "Стійкий/міцний", "B1"),
  w("Tijdelijk", "Временный", "Temporary", "Тимчасовий", "B1"),
  w("Positief", "Положительный", "Positive", "Позитивний", "B1"),
  w("Negatief", "Отрицательный", "Negative", "Негативний", "B1"),
  w("Essentieel", "Существенный", "Essential", "Суттєвий", "B1"),
  // Culture
  w("Traditie", "Традиция", "Tradition", "Традиція", "B1"),
  w("Cultuur", "Культура", "Culture", "Культура", "B1"),
  w("Geschiedenis", "История", "History", "Історія", "B1"),
  w("Technologie", "Технология", "Technology", "Технологія", "B1"),
  w("Innovatie", "Инновация", "Innovation", "Інновація", "B1"),
  w("Globalisering", "Глобализация", "Globalization", "Глобалізація", "B1"),
  w("Diversiteit", "Разнообразие", "Diversity", "Різноманітність", "B1"),
  w("Waarde", "Ценность", "Value", "Цінність", "B1"),
  // Psychology
  w("Gedrag", "Поведение", "Behavior", "Поведінка", "B1"),
  w("Persoonlijkheid", "Личность", "Personality", "Особистість", "B1"),
  w("Emotie", "Эмоция", "Emotion", "Емоція", "B1"),
  w("Motivatie", "Мотивация", "Motivation", "Мотивація", "B1"),
  w("Talent", "Талант", "Talent", "Талант", "B1"),
  w("Intelligentie", "Интеллект", "Intelligence", "Інтелект", "B1"),
  w("Concentratie", "Концентрация", "Concentration", "Концентрація", "B1"),
  w("Aandacht", "Внимание", "Attention", "Увага", "B1"),
  w("Geheugen", "Память", "Memory", "Пам'ять", "B1"),
  w("Zelfvertrouwen", "Уверенность в себе", "Self-confidence", "Впевненість у собі", "B1"),
  // Social issues
  w("Armoede", "Бедность", "Poverty", "Бідність", "B1"),
  w("Criminaliteit", "Преступность", "Crime", "Злочинність", "B1"),
  w("Vluchteling", "Беженец", "Refugee", "Біженець", "B1"),
  w("Werkgelegenheid", "Занятость", "Employment", "Зайнятість", "B1"),
  // Technology B1
  w("Software", "Программное обеспечение", "Software", "Програмне забезпечення", "B1"),
  w("Applicatie", "Приложение", "Application", "Додаток", "B1"),
  w("Netwerk", "Сеть", "Network", "Мережа", "B1"),
  w("Privacy", "Конфиденциальность", "Privacy", "Конфіденційність", "B1"),
  w("Automatisering", "Автоматизация", "Automation", "Автоматизація", "B1"),
  // Education system
  w("Basisschool", "Начальная школа", "Primary school", "Початкова школа", "B1"),
  w("Middelbare school", "Средняя школа", "Secondary school", "Середня школа", "B1"),
  w("Scriptie", "Дипломная работа", "Thesis", "Дипломна робота", "B1"),
  w("Beurs", "Стипендия", "Scholarship", "Стипендія", "B1"),
  // More verbs
  w("Vaststellen", "Устанавливать", "To determine", "Встановлювати", "B1"),
  w("Concluderen", "Делать вывод", "To conclude", "Робити висновок", "B1"),
  w("Formuleren", "Формулировать", "To formulate", "Формулювати", "B1"),
  w("Investeren", "Инвестировать", "To invest", "Інвестувати", "B1"),
  // Dutch society
  w("Tolerantie", "Терпимость", "Tolerance", "Толерантність", "B1"),
  w("Overleg", "Обсуждение", "Consultation", "Обговорення", "B1"),
  w("Consensus", "Консенсус", "Consensus", "Консенсус", "B1"),
  w("Compromis", "Компромисс", "Compromise", "Компроміс", "B1"),
  w("Rijbewijs", "Водительские права", "Driver's license", "Водійські права", "B1"),
  // More adjectives
  w("Efficiënt", "Эффективный", "Efficient", "Ефективний", "B1"),
  w("Relevant", "Актуальный", "Relevant", "Актуальний", "B1"),
  w("Potentieel", "Потенциальный", "Potential", "Потенційний", "B1"),
  w("Objectief", "Объективный", "Objective", "Об'єктивний", "B1"),
  w("Kritisch", "Критический", "Critical", "Критичний", "B1"),
  w("Kwetsbaar", "Уязвимый", "Vulnerable", "Вразливий", "B1"),
  w("Complex", "Сложный", "Complex", "Складний", "B1"),

  // ===== B2 - UPPER INTERMEDIATE =====
  // Politics & Government
  w("Beleid", "Политика/курс", "Policy", "Політика/курс", "B2"),
  w("Hervorming", "Реформа", "Reform", "Реформа", "B2"),
  w("Transparantie", "Прозрачность", "Transparency", "Прозорість", "B2"),
  w("Grondwet", "Конституция", "Constitution", "Конституція", "B2"),
  w("Parlement", "Парламент", "Parliament", "Парламент", "B2"),
  w("Coalitie", "Коалиция", "Coalition", "Коаліція", "B2"),
  w("Oppositie", "Оппозиция", "Opposition", "Опозиція", "B2"),
  w("Ideologie", "Идеология", "Ideology", "Ідеологія", "B2"),
  // Advanced verbs
  w("Uitdagen", "Бросать вызов", "To challenge", "Кидати виклик", "B2"),
  w("Overtuigen", "Убеждать", "To convince", "Переконувати", "B2"),
  w("Betwisten", "Оспаривать", "To dispute", "Оскаржувати", "B2"),
  w("Implementeren", "Внедрять", "To implement", "Впроваджувати", "B2"),
  w("Integreren", "Интегрировать", "To integrate", "Інтегрувати", "B2"),
  w("Optimaliseren", "Оптимизировать", "To optimize", "Оптимізувати", "B2"),
  w("Reguleren", "Регулировать", "To regulate", "Регулювати", "B2"),
  w("Moderniseren", "Модернизировать", "To modernize", "Модернізувати", "B2"),
  // Science
  w("Genetica", "Генетика", "Genetics", "Генетика", "B2"),
  w("Ecologie", "Экология", "Ecology", "Екологія", "B2"),
  w("Astronomie", "Астрономия", "Astronomy", "Астрономія", "B2"),
  w("Linguïstiek", "Лингвистика", "Linguistics", "Лінгвістика", "B2"),
  w("Biotechnologie", "Биотехнология", "Biotechnology", "Біотехнологія", "B2"),
  w("Evolutie", "Эволюция", "Evolution", "Еволюція", "B2"),
  // Philosophy
  w("Existentie", "Существование", "Existence", "Існування", "B2"),
  w("Perceptie", "Восприятие", "Perception", "Сприйняття", "B2"),
  w("Intuïtie", "Интуиция", "Intuition", "Інтуїція", "B2"),
  w("Paradox", "Парадокс", "Paradox", "Парадокс", "B2"),
  w("Dilemma", "Дилемма", "Dilemma", "Дилема", "B2"),
  w("Empathie", "Эмпатия", "Empathy", "Емпатія", "B2"),
  // Law
  w("Rechtbank", "Суд", "Court", "Суд", "B2"),
  w("Rechter", "Судья", "Judge", "Суддя", "B2"),
  w("Aanklager", "Прокурор", "Prosecutor", "Прокурор", "B2"),
  w("Verdachte", "Подозреваемый", "Suspect", "Підозрюваний", "B2"),
  w("Getuige", "Свидетель", "Witness", "Свідок", "B2"),
  w("Vonnis", "Приговор", "Verdict", "Вирок", "B2"),
  w("Misdaad", "Преступление", "Crime", "Злочин", "B2"),
  w("Fraude", "Мошенничество", "Fraud", "Шахрайство", "B2"),
  w("Discriminatie", "Дискриминация", "Discrimination", "Дискримінація", "B2"),
  w("Mensenrechten", "Права человека", "Human rights", "Права людини", "B2"),
  // Economy advanced
  w("Werkloosheid", "Безработица", "Unemployment", "Безробіття", "B2"),
  w("Recessie", "Рецессия", "Recession", "Рецесія", "B2"),
  w("Inflatie", "Инфляция", "Inflation", "Інфляція", "B2"),
  w("Wisselkoers", "Обменный курс", "Exchange rate", "Обмінний курс", "B2"),
  w("Fusie", "Слияние", "Merger", "Злиття", "B2"),
  // Advanced adjectives
  w("Controversieel", "Спорный", "Controversial", "Суперечливий", "B2"),
  w("Hypothetisch", "Гипотетический", "Hypothetical", "Гіпотетичний", "B2"),
  w("Autonoom", "Автономный", "Autonomous", "Автономний", "B2"),
  w("Pragmatisch", "Прагматичный", "Pragmatic", "Прагматичний", "B2"),
  w("Sceptisch", "Скептичный", "Skeptical", "Скептичний", "B2"),
  w("Systematisch", "Систематический", "Systematic", "Систематичний", "B2"),
  w("Authentiek", "Аутентичный", "Authentic", "Автентичний", "B2"),
  w("Uniek", "Уникальный", "Unique", "Унікальний", "B2"),
  // Arts & Culture
  w("Architectuur", "Архитектура", "Architecture", "Архітектура", "B2"),
  w("Literatuur", "Литература", "Literature", "Література", "B2"),
  w("Poëzie", "Поэзия", "Poetry", "Поезія", "B2"),
  w("Esthetiek", "Эстетика", "Aesthetics", "Естетика", "B2"),
  w("Inspiratie", "Вдохновение", "Inspiration", "Натхнення", "B2"),
  w("Erfgoed", "Наследие", "Heritage", "Спадщина", "B2"),
  // More B2
  w("Uitdaging", "Вызов", "Challenge", "Виклик", "B2"),
  w("Ontwikkeling", "Развитие", "Development", "Розвиток", "B2"),
  w("Duurzaamheid", "Устойчивость", "Sustainability", "Сталість", "B2"),
  w("Invloed", "Влияние", "Influence", "Вплив", "B2"),
  w("Ingewikkeld", "Сложный", "Complicated", "Складний", "B2"),
  w("Toekomst", "Будущее", "Future", "Майбутнє", "B2"),
  w("Mogelijkheid", "Возможность", "Possibility", "Можливість", "B2"),
  w("Perspectief", "Перспектива", "Perspective", "Перспектива", "B2"),
  w("Samenleving", "Общество", "Society", "Суспільство", "B2"),
  w("Vooruitgang", "Прогресс", "Progress", "Прогрес", "B2"),
  w("Kritiek", "Критика", "Criticism", "Критика", "B2"),
  w("Interpretatie", "Интерпретация", "Interpretation", "Інтерпретація", "B2"),
  w("Nuance", "Нюанс", "Nuance", "Нюанс", "B2"),
  w("Complexiteit", "Сложность", "Complexity", "Складність", "B2"),
  w("Metafoor", "Метафора", "Metaphor", "Метафора", "B2"),
  w("Ironie", "Ирония", "Irony", "Іронія", "B2"),
  w("Retoriek", "Риторика", "Rhetoric", "Риторика", "B2"),
  w("Fenomeen", "Феномен", "Phenomenon", "Феномен", "B2"),
  w("Paradigma", "Парадигма", "Paradigm", "Парадигма", "B2"),
  w("Stereotype", "Стереотип", "Stereotype", "Стереотип", "B2"),
  w("Vooroordeel", "Предрассудок", "Prejudice", "Упередження", "B2"),
  w("Tolerantie", "Толерантность", "Tolerance", "Толерантність", "B2"),
  // Diplomacy
  w("Diplomatie", "Дипломатия", "Diplomacy", "Дипломатія", "B2"),
  w("Verdrag", "Договор", "Treaty", "Договір", "B2"),
  w("Sanctie", "Санкция", "Sanction", "Санкція", "B2"),
  w("Soevereiniteit", "Суверенитет", "Sovereignty", "Суверенітет", "B2"),
  // More advanced verbs
  w("Nuanceren", "Нюансировать", "To nuance", "Нюансувати", "B2"),
  w("Reflecteren", "Рефлексировать", "To reflect", "Рефлексувати", "B2"),
  w("Generaliseren", "Обобщать", "To generalize", "Узагальнювати", "B2"),
  w("Specialiseren", "Специализироваться", "To specialize", "Спеціалізуватися", "B2"),
  w("Consolideren", "Консолидировать", "To consolidate", "Консолідувати", "B2"),
  // Literature
  w("Allegorie", "Аллегория", "Allegory", "Алегорія", "B2"),
  w("Satire", "Сатира", "Satire", "Сатира", "B2"),
  w("Genre", "Жанр", "Genre", "Жанр", "B2"),
  w("Narratief", "Нарратив", "Narrative", "Наратив", "B2"),
  w("Protagonist", "Главный герой", "Protagonist", "Головний герой", "B2"),
  // Media advanced
  w("Censuur", "Цензура", "Censorship", "Цензура", "B2"),
  w("Persvrijheid", "Свобода прессы", "Freedom of the press", "Свобода преси", "B2"),
  w("Desinformatie", "Дезинформация", "Disinformation", "Дезінформація", "B2"),
  w("Propaganda", "Пропаганда", "Propaganda", "Пропаганда", "B2"),
  // Science advanced
  w("Molecuul", "Молекула", "Molecule", "Молекула", "B2"),
  w("Atoom", "Атом", "Atom", "Атом", "B2"),
  w("Cel", "Клетка", "Cell", "Клітина", "B2"),
  w("DNA", "ДНК", "DNA", "ДНК", "B2"),
  w("Gen", "Ген", "Gene", "Ген", "B2"),
  w("Vaccin", "Вакцина", "Vaccine", "Вакцина", "B2"),
];
